apiVersion: v1
data:
  prometheus-config: |2-
        scrape_configs:
        - job_name: e4k
          scrape_interval: 1m
          static_configs:
          - targets:
            - aio-mq-diagnostics-service.azure-iot-operations.svc.cluster.local:9600
        - job_name: nats
          scrape_interval: 1m
          static_configs:
          - targets:
            - aio-dp-msg-store-0.aio-dp-msg-store-headless.azure-iot-operations.svc.cluster.local:7777
        - job_name: otel
          scrape_interval: 1m
          static_configs:
          - targets:
            - aio-otel-collector.azure-iot-operations.svc.cluster.local:8889
        - job_name: aio-annotated-pod-metrics
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - action: drop
            regex: true
            source_labels:
            - __meta_kubernetes_pod_container_init
          - action: keep
            regex: true
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          - action: replace
            regex: ([^:]+)(?::\\d+)?;(\\d+)
            replacement: $1:$2
            source_labels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
            target_label: __address__
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: kubernetes_namespace
          - action: keep
            regex: 'azure-iot-operations'
            source_labels:
            - kubernetes_namespace
          scrape_interval: 1m
kind: ConfigMap
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system