{
 "title": "AIO Sample Dashboard",
 "description": "Sample dashboard for viewing Azure IoT Operations health and usage",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(max by(cluster)(max_over_time(up{job=\"kube-state-metrics\"}[$__range])))"
    }
   },
   { "name": "namespace", "query": "azure-iot-operations" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "cluster",
   "options": {
    "content": "<div style=\"background-color:black; text-align: center\"> \n  <span style=\"color:#C1C9D1; font-size:16px\">[$cluster]</span>\n</div>\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "repeat": "cluster",
   "options": {
    "content": "<div style=\"background-color:#C1C9D1; text-align: center\"> \n  <span style=\"color:black; font-size:16px\">AIO Health Model</span>\n</div>\n\n"
   }
  },
  {
   "title": "AIO Broker Health [$cluster]",
   "type": "state-timeline",
   "description": "Health Status of the MQTT Broker as perceived by the Diagnostics Probe",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "label_replace(\r\n  sum(\r\n    sum_over_time(\r\n      aio_broker_connect_route_replication_correctness{cluster=\"$cluster\"}[10m]\r\n    )\r\n  )\r\n  /\r\n  sum(\r\n    count_over_time(\r\n      aio_broker_connect_route_replication_correctness{cluster=\"$cluster\"}[10m]\r\n    )\r\n  ) OR on() vector(404),\r\n  \"_\", \"Connect\", \"__name__\", \".*\"\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(\r\n    sum_over_time(\r\n      aio_broker_publish_route_replication_correctness{cluster=\"$cluster\"}[10m]\r\n    )\r\n  )\r\n  /\r\n  sum(\r\n    count_over_time(\r\n      aio_broker_publish_route_replication_correctness{cluster=\"$cluster\"}[10m]\r\n    )\r\n  ) OR on() vector(404),\r\n  \"_\", \"Publish\", \"__name__\", \".*\"\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(\r\n    sum_over_time(\r\n      aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\"}[10m]\r\n    )\r\n  )\r\n  /\r\n  sum(\r\n    count_over_time(\r\n      aio_broker_subscribe_route_replication_correctness{cluster=\"$cluster\"}[10m]\r\n    )\r\n  ) OR on() vector(404),\r\n  \"_\", \"Subscribe\", \"__name__\", \".*\"\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  (\r\n    sum( # Total signals for 10m\r\n      count_over_time(\r\n        aio_broker_message_delivery_check_total_timeouts{cluster=\"$cluster\"}[10m]\r\n      )\r\n    )\r\n    -\r\n    sum( # Total failures for 10m\r\n      sum_over_time(\r\n        aio_broker_message_delivery_check_total_timeouts{cluster=\"$cluster\"}[10m]\r\n      )\r\n    )\r\n  )\r\n  / # Divide by total signals to get success rate\r\n  sum( \r\n    count_over_time(\r\n      aio_broker_message_delivery_check_total_timeouts{cluster=\"$cluster\"}[10m]\r\n    )\r\n  ) OR on() vector(404),\r\n  \"_\", \"Message Delivery\", \"__name__\", \".*\"\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(\r\n    sum_over_time(\r\n      aio_broker_ping_correctness{cluster=\"$cluster\"}[10m]\r\n    )\r\n  )\r\n  /\r\n  sum(\r\n    count_over_time(\r\n      aio_broker_ping_correctness{cluster=\"$cluster\"}[10m]\r\n    )\r\n  ) OR on() vector(404),\r\n  \"_\", \"Ping\", \"__name__\", \".*\"\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AIO Dataflow Health [$cluster]",
   "type": "state-timeline",
   "description": "Health Status of Dataflow Operator",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "label_replace(\r\n  sum by (_) (\r\n    1 - max_over_time(\r\n      aio_dataflow_reconcile_errors{cluster=\"$cluster\"}[1m]\r\n    )\r\n  ) OR on() vector(1),\r\n  \"_\",\r\n  \"Operator Health\",\r\n  \"__name__\",\r\n  \".*\"\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Errors [$cluster]",
   "type": "timeseries",
   "description": "Including:\n- Backpressure\n- Authentication Failures\n- Authorization Failures\n- Dropped QoS0 Messages\n- Dataflow Errors\n- Connector Errors",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by(_)(label_replace(\r\n        0 < increase(aio_broker_authentication_failures{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:authn_failure','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_broker_authorization_failures{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:authz_failure','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_broker_backpressure_packets_rejected_memory{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:backpressure_memory','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_broker_backpressure_packets_rejected_disk{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:backpressure_disk','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_broker_qos0_messages_dropped{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:qos0_msgs_dropped','','')) or\r\nvector(0) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(_)(label_replace(\r\n        increase(aio_opc_mqtt_message_publishing_duration_count{\r\n            cluster=\"$cluster\",aio_opc_mqtt_publish_result!~\"(success|nomatchingsubscribers)\"\r\n        }[5m:1m])\r\n    ,'_','Connector:publishError:$1','aio_opc_mqtt_publish_result','(.*)')) or\r\nsum by (_)(label_replace(\r\n        increase(aio_opc_session_connect_duration_count{\r\n            cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_connect_result!=\"success\"\r\n        }[5m:1m])\r\n    ,'_','Connector:connectError:$1','aio_opc_connect_result','(.*)')) or\r\nvector(0)>0 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (_)(\r\n    label_replace(increase(aio_dataflow_errors{cluster='$cluster'}[5m:1m]),'_','Dataflows:$1','errorcode','(.*)')\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AIO Kubernetes Workload Health [$cluster]",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\"$namespacem\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n  / label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_statefulset_status_replicas{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(404),\"_\",\"AIO Workload Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Restart Health:\r\n############################\r\nlabel_replace(\r\n  sgn(sum_over_time(sum(rate(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[10m:1m]\r\n    )*60)[1h:]) > 5) * 0.0 # RED: Cumulative restarts over X(5) time greater than Y(1h)\r\n  or sgn(max(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n    + 1 >= 0))\r\n  ,\"_\",\"AIO Container Restarts\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container CPU top-level health\r\n################################\r\nlabel_replace(\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m])\r\n    >= 0.80)\r\n    ) \r\n    * 0.0\r\nor\r\nmin(\r\n    sgn(min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"cpu\"}) by (namespace,container))\r\n    )\r\n,\"_\",\"AIO Container CPU\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Memory Health:\r\n###########################\r\nlabel_replace(\r\nmin( # Look for high memory utilization\r\n    0.0 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace, container)\r\n    ) >= .95) or # show health state of 0 if container memory utilization >= 95%\r\n    vector(0)>0\r\n)\r\nor\r\nmin(\r\n    sgn(min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace,container))\r\n)\r\n,\"_\",\"AIO Container Memory\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AIO K8s Workload Details [$cluster]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "label_replace(sum (\r\n    label_replace(label_join(\r\n        kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*\"} or\r\n        kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\".*\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n),\"_\",\"Ready\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n    sum(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*\"} or\r\n        kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\".*\"} or\r\n        kube_statefulset_status_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*\"}\r\n    ) - sum (\r\n    label_replace(label_join(\r\n        kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*\"} or\r\n        kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\".*\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n),\"_\",\"NOT-Ready\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Container Restarts\r\nlabel_replace(ceil(sum(increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\".*\"}[$__rate_interval]))),\"_\",\"Restarts\",\"\",\"\") > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\".*\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(label_replace(sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\".*\",container!=\"\"})/(1024*1024),\"_\",\"Mem Working Bytes (MB)\",\"\",\"\") )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Node Health [$cluster]",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "# Node Health Status\r\n####################\r\nlabel_replace(\r\n  sum(\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition=\"ready\",status=\"false\"} > 0) * 0 or\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition=\"ready\",status=\"true\"} > 0) * 1\r\n  ) / sum(kube_node_info{cluster=\"$cluster\"})\r\n  ,\"_\",\"Node Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Node CPU Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\"}[5m])) \r\n              + avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\"}[5m]))\r\n        ) * 100) > 90)\r\n    or 1.0 * sgn(sum by (instance)(node_cpu_seconds_total{cluster=\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n    ,\"_\",\"$1\",\"instance\",\"(.*)\"))\r\n# END inner query\r\n),\"_\",\"Node CPU\", \"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Node Memory Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        (100 * sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - (node_memory_MemFree_bytes{cluster=\"$cluster\"} + node_memory_Buffers_bytes{cluster=\"$cluster\"} + node_memory_Cached_bytes{cluster=\"$cluster\"})) / sum by(instance) (node_memory_MemTotal_bytes{cluster=\"$cluster\"})) > 90)\r\n    or 1.0 * sgn(sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n,\"_\",\"$1\",\"instance\",\"(.*)\"))\r\n# END inner query\r\n),\"_\",\"Node Memory\", \"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Disk Usage Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(node)(label_replace(vector(0)>0\r\n  or 0.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"}) > 10) > 90)\r\n  or 1.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"})))\r\n,\"node\",\"$1\",\"instance\",\"(.*)\"))\r\nor max by (node) (kube_node_info{cluster=\"$cluster\"}) * -1 # Baseline by node\r\n# END inner query\r\n),\"_\",\"Node Disk\", \"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Utilization [$cluster]",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "#############################\r\n# Node CPU Usage Pecent\r\nmax by (node) (label_replace(\r\n  100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\"}[5m])) \r\n        + avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\"}[5m]))\r\n  ) * 100)\r\n  #* on (instance) group_left(node) label_replace(max by(internal_ip,node) (kube_node_info),\"instance\",\"$1:9100\",\"internal_ip\",\"(.*)\") # Node Info\r\n  ,\"node\",\"$1\",\"instance\",\"(.*)\")\r\n)\r\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization [$cluster]",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "#############################\r\n# Node Memory Usage Pecent\r\n  min by (node) (label_replace(\r\n    (100 * sum by (instance)\r\n      (node_memory_MemTotal_bytes{cluster=\"$cluster\"} \r\n      - node_memory_MemFree_bytes{cluster=\"$cluster\"} \r\n      - node_memory_Buffers_bytes{cluster=\"$cluster\"} \r\n      - node_memory_Cached_bytes{cluster=\"$cluster\"}) \r\n    / sum by(instance) (node_memory_MemTotal_bytes{cluster=\"$cluster\"}))\r\n    #* on (instance) group_left(node) label_replace(\r\n    #  max by(internal_ip,node) (kube_node_info),\"instance\",\"$1:9100\",\"internal_ip\",\"(.*)\") # Node Info\r\n      ,\"node\",\"$1\",\"instance\",\"(.*)\")\r\n  )\r\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Disk Capacity [$cluster]",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "#############################\r\n# Disk Usage\r\nmax by (node,device) (label_replace(\r\n  #min by(instance,device) (100 - (100 * node_filesystem_free_bytes{cluster=\"$cluster\"} / node_filesystem_size_bytes{cluster=\"$cluster\"}) > 5)\r\n  min by(instance,device) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} / node_filesystem_size_bytes{cluster=\"$cluster\"}) > 10)\r\n    #* on (instance) group_left(node) label_replace(max by(internal_ip,node) (kube_node_info),\"instance\",\"$1:9100\",\"internal_ip\",\"(.*)\") # Node Info\r\n      ,\"node\",\"$1\",\"instance\",\"(.*)\")\r\n)\r\n#or label_replace(vector(60),\"threshold\",\"redline\",\"\",\"\")\r\n",
     "legendFormat": "{{node}}({{device}})"
    }
   ]
  },
  { "title": " ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
   "repeat": "cluster",
   "options": {
    "content": "<div style=\"background-color:#C1C9D1; text-align: center\"> \n  <span style=\"color:black; font-size:16px\">Connectors</span>\n</div>\n\n"
   }
  },
  {
   "title": "Connector (OPC-UA) Assets and DataPoints [$cluster]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by(_)(\r\n    label_replace(\r\n        aio_opc_asset_count{cluster='$cluster'}\r\n    ,'_','assets','','')\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(_)(\r\n    label_replace(\r\n        aio_opc_asset_datapoint_count{cluster='$cluster'}\r\n    ,'_','datapoints','','')\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": " ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 },
   "repeat": "cluster",
   "options": {
    "content": "<div style=\"background-color:#C1C9D1; text-align: center\"> \n  <span style=\"color:black; font-size:16px\">Broker</span>\n</div>\n\n"
   }
  },
  {
   "title": "Broker Sessions [$cluster]",
   "type": "timeseries",
   "description": "All active sessions",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by(_)(\r\n    label_replace(\r\n        aio_broker_store_total_sessions{cluster='$cluster'}\r\n    ,'_','sessions','','')\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Subscriptions [$cluster]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by(_)(\r\n    label_replace(\r\n        aio_broker_store_subscriptions{cluster='$cluster'}\r\n    ,'_','subscriptions','','')\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(_)(\r\n    label_replace(\r\n        aio_broker_store_shared_subscriptions{cluster='$cluster'}\r\n    ,'_','shared subscriptions','','')\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Incoming Publishes by Category [$cluster]",
   "type": "timeseries",
   "description": "Rate per Minute",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 68 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by(category)(\r\n    label_replace(\r\n        rate(aio_broker_publishes_received{cluster='$cluster',category!=''}[1m]) * 60\r\n    ,'_',' $1','category','(.*)')\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Incoming Publishes Size by Category [$cluster]",
   "type": "timeseries",
   "description": "Rate per Minute",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 76 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(category)(\r\n    label_replace(\r\n        rate(aio_broker_payload_bytes_received{cluster='$cluster',category!=''}[1m]) * 60\r\n    ,'_',' $1','category','(.*)')\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Outgoing Publishes by Category [$cluster]",
   "type": "timeseries",
   "description": "Rate per Minute",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 84 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by(_)(\r\n    label_replace(\r\n        rate(aio_broker_publishes_sent{cluster='$cluster',category!=''}[1m]) * 60\r\n    ,'_',' $1','category','(.*)')\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": " ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Broker Outgoing Publishes Size by Category [$cluster]",
   "type": "timeseries",
   "description": "Rate per Minute",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 93 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(category)(\r\n    label_replace(\r\n        rate(aio_broker_payload_bytes_sent{cluster='$cluster',category!=''}[1m]) * 60\r\n    ,'_',' $1','category','(.*)')\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 101 },
   "repeat": "cluster",
   "options": {
    "content": "<div style=\"background-color:#C1C9D1; text-align: center\"> \n  <span style=\"color:black; font-size:16px\">Dataflows</span>\n</div>\n\n"
   }
  },
  {
   "title": "Active Dataflows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 103 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aio_dataflow_active_dataflows{cluster='$cluster'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Dataflow Graphs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 103 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aio_dataflow_active_dataflow_graphs{cluster='$cluster'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataflows Messages Received by EndPointType[$cluster]",
   "type": "timeseries",
   "description": "Rate per Minute",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 109 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by(source_service_type)(rate(aio_dataflow_messages_received{cluster='$cluster'}[1m]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataflows Messages Sent by EndPointType and DataflowId [$cluster]",
   "type": "timeseries",
   "description": "Rate per Minute",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 118 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by(target_service_type)(rate(aio_dataflow_messages_sent{cluster='$cluster'}[1m]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataflows Processing Latency by EndPointType [$cluster]",
   "type": "timeseries",
   "description": "P95 and P50",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 106 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, source_service_type) (\r\n    rate(aio_dataflow_processing_latency_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "p95 {{source_service_type}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le, source_service_type) (\r\n    rate(aio_dataflow_processing_latency_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "p50 {{source_service_type}}"
    }
   ]
  }
 ]
}