{
 "title": "aio-service-dp-stage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_condition,cluster)"
    }
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": {
     "query": "label_values(aio_dp_runner_info{cluster=\"$cluster\"},cloud_resource_id)"
    }
   },
   {
    "name": "stage",
    "label": "Stage",
    "query": {
     "query": "label_values(aio_dp_stage_info{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"},stage_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Stage Name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aio_dp_stage_info{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}) by (stage_id)",
     "legendFormat": "{{stage_name}}"
    }
   ]
  },
  {
   "title": "Stage Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aio_dp_stage_info{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}) by (stage_type)",
     "legendFormat": "{{stage_type}}"
    }
   ]
  },
  {
   "title": "Incoming Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_outgoing_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((histogram_quantile(0.95, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval])) by (le)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval]))",
     "legendFormat": "$pipeline/$stage"
    }
   ]
  },
  {
   "title": "Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_outgoing_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval]))",
     "legendFormat": "$pipeline/$stage"
    }
   ]
  },
  {
   "title": "Stage Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Runner Partition Active Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (runner_partition) (rate(aio_dp_stage_latency_sum{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}[$__rate_interval])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Code",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$stage\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}