{
 "title": "aio-service-layered-network-management",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "component", "query": "${VAR_COMPONENT}" },
   { "name": "component_text", "query": "${VAR_COMPONENT_TEXT}" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=~\"$cluster\", phase!~\"terminating\"}"
    }
   },
   { "name": "latency_percentile", "query": "${VAR_LATENCY_PERCENTILE}" },
   { "name": "latency_quantile_range", "query": "5m,10m,15m,1h,3h,6h" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#283747\">\n  <span style=\"color:#FFFFF8; font-size:28px\">Azure Edge Services - ${component_text} Health</span>\n</div>\n<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Scenario Health (SLO/RUM) related to ${component_text}</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(cluster, podname, level, instance, job, level, service_name) (rate(server_uptime{cluster=\"$cluster\"}[5m])) > bool 0",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Golden Metrics</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (level, custom_resource_name, instance, job, podname,service_name) (server_total_connections{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Data sent to upper level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (custom_resource_name, envoy_tcp_prefix, instance, job, level,podname,service_name) (rate(tcp_downstream_cx_rx_bytes_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Data received from upper level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (custom_resource_name, envoy_tcp_prefix, instance, job, level,podnameservice_name) (rate(tcp_downstream_cx_tx_bytes_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Inspector SNI found",
   "type": "timeseries",
   "description": "Total number of times Server Name Indication was found",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(tls_inspector_sni_found{cluster=\"$cluster\", podname=~\"$component\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Inspector SNI Not Found",
   "type": "timeseries",
   "description": "Total number of times Server Name Indication was not found.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(tls_inspector_sni_not_found{cluster=\"$cluster\", podname=~\"$component\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Infrastructure Workload Health</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "description": "CPU usage of LNM pods in millicore",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"$component\", cluster=\"$cluster\"}[$__rate_interval]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\".*\", pod=~\"$component\", container!=\"\"}/(1024*1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Errors & Logs</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last 10 Kube Events entries (from $cluster)",
   "type": "table",
   "description": "work in progress",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubeEvents\r\n| where TimeGenerated > $__timeFrom() and TimeGenerated  <= $__timeTo\r\n| where ClusterName == '$cluster'\r\n| order by LastSeen desc, FirstSeen desc, TimeGenerated desc\r\n| project-rename PodName = Name\r\n| project FirstSeen, LastSeen, Count, PodName, Reason, Message\r\n| take 10",
      "resources": [
       "/subscriptions/<Placeholder_SubID>"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}