{
 "title": "aio-service-mq-state-store",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=~\"$cluster\", phase!~\"terminating\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "State Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Key Insertions / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "insertions/s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_mq_state_store_insertions{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) / count(kube_pod_info{pod=~\"aio-mq-dmqtt-backend.*0\",cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Key modifications / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "modifications/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_mq_state_store_modifications{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) / count(kube_pod_info{pod=~\"aio-mq-dmqtt-backend.*0\",cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retrievals / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "retrievals/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_mq_state_store_retrievals{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) / count(kube_pod_info{pod=~\"aio-mq-dmqtt-backend.*0\",cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deletions / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deletions/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_mq_state_store_deletions{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) / count(kube_pod_info{pod=~\"aio-mq-dmqtt-backend.*0\",cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}