{
 "title": "aio-service-mq-publish",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=~\"$cluster\", phase!~\"terminating\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Publish Health [%] (Avg)",
   "type": "timeseries",
   "description": "Publish health represents the health of the E4K broker. It is calculated as an average value of replication correctness for each route",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "columns": [
      { "selector": "Correctness", "text": "Health", "type": "number" },
      { "selector": "Time", "text": "Time", "type": "timestamp" }
     ],
     "expr": "avg(aio_mq_publish_route_replication_correctness{cluster=~\"$cluster\", instance=~\"$namespace\"})",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Publish Health [%] (Avg) per route",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aio_mq_publish_route_replication_correctness{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg publish latency [ms] (99th pctl)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "columns": [
      { "selector": "Time", "text": "Time", "type": "timestamp" },
      { "selector": "Mu", "text": "Publish Latency Average", "type": "number" }
     ],
     "expr": "aio_mq_publish_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Mean",
     "parser": "simple"
    }
   ]
  },
  {
   "title": "Std dev publish latency [ms] (99th pctl)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "columns": [
      { "selector": "Time", "text": "Time", "type": "timestamp" },
      { "selector": "Sigma", "text": "Publish Latency Variance", "type": "number" }
     ],
     "expr": "aio_mq_publish_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Standard deviation"
    }
   ]
  },
  {
   "title": "Avg publish latency [ms] (99th pctl) Control Chart",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "columns": [
      { "selector": "Time", "text": "Time", "type": "timestamp" },
      { "selector": "Mu", "text": "Avg Publish Latency", "type": "number" },
      { "selector": "Min1Sigma", "text": "Minus 1 Sigma", "type": "number" },
      { "selector": "Min2Sigma", "text": "Minus 2 Sigma", "type": "number" },
      { "selector": "LCL", "text": "LCL", "type": "number" },
      { "selector": "Plus1Sigma", "text": "Plus 1 Sigma", "type": "number" },
      { "selector": "Plus2Sigma", "text": "Plus 2 Sigma", "type": "number" },
      { "selector": "UCL", "text": "UCL", "type": "number" },
      { "selector": "LastReading", "text": "Last reading", "type": "number" }
     ],
     "expr": "aio_mq_publish_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Mean",
     "parser": "simple"
    },
    {
     "expr": "aio_mq_publish_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} - aio_mq_publish_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "1 Std Dev"
    },
    {
     "expr": "aio_mq_publish_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} - 2*aio_mq_publish_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "2 Std Dev"
    },
    {
     "expr": "aio_mq_publish_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} - 3*aio_mq_publish_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "LCL"
    },
    {
     "expr": "aio_mq_publish_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} + aio_mq_publish_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "1 Std Dev"
    },
    {
     "expr": "aio_mq_publish_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} + 2*aio_mq_publish_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "2 Std Dev"
    },
    {
     "expr": "aio_mq_publish_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} + 3*aio_mq_publish_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "UCL"
    },
    {
     "expr": "aio_mq_publish_latency_last_value_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Last"
    }
   ]
  },
  {
   "title": "Publish message latency per route [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aio_mq_publish_latency_route_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}