{
 "title": "aio-service-mq-bridges",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "bridge", "query": { "query": "active_connections_count" } },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=\"$cluster\", phase!~\"terminating\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections to local broker ($bridge)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "repeat": "bridge",
   "targets": [
    {
     "expr": "aio_mq_active_connections_count{type=\"local\", pod_id=\"$bridge\", cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Nb connections to local broker"
    }
   ]
  },
  {
   "title": "Connections to remote broker ($bridge)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "repeat": "bridge",
   "targets": [
    {
     "expr": "aio_mq_active_connections_count{type=\"remote\", pod_id=\"$bridge\", cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Nb connections to remote broker"
    }
   ]
  },
  {
   "title": "Number of routes ($bridge)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "repeat": "bridge",
   "targets": [
    {
     "expr": "aio_mq_number_of_routes{pod_id=\"$bridge\", cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Nb of routes"
    }
   ]
  },
  {
   "title": "Publishes processed ($bridge)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "repeat": "bridge",
   "targets": [
    {
     "expr": "aio_mq_publishes_processed{pod_id=\"$bridge\", cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  }
 ]
}