{
 "title": "aio-service-mq-main",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=\"$cluster\", phase!~\"terminating\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency (selftest traffic only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Avg publish latency [ms] (99th pctl)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aio_mq_publish_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Std dev publish latency [ms] (99th pctl)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aio_mq_publish_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg subscribe latency [ms] (99th pctl)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aio_mq_subscribe_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Std dev subscribe latency [ms] (99th pctl)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aio_mq_subscribe_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg unsubscribe latency [ms] (99th pctl)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aio_mq_unsubscribe_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Std dev unsubscribe latency [ms] (99th pctl)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aio_mq_unsubscribe_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg end-to-end latency [ms] (99th pctl)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aio_mq_payload_check_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Std dev end-to-end latency [ms] (99th pctl)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aio_mq_payload_check_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Health (selftest traffic only)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Last publish health [%]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aio_mq_publish_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of pods",
   "type": "stat",
   "description": "Total number of MQ pods",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"aio-mq.*\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last subscribe health [%]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods with high memory (300 MiB or more)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod) (container_memory_working_set_bytes{pod=~\"aio-mq.*\", container!=\"\", cluster=\"$cluster\", instance=~\"$namespace\"} / (1024*1024)) > 300) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last unsubscribe health [%]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aio_mq_unsubscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods with high CPU (5 millicores or more)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"aio-mq.*\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval]) * 1000) > 5) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last end-to-end health [%]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - min(\r\n    0 * sgn(\r\n        sum(aio_mq_payload_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n    <= 0) or\r\n    1 * sgn(\r\n        sum(aio_mq_payload_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n    > 0)) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods with 5 or more restarts in the last 5 mins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod)(changes(kube_pod_status_ready{pod=~\"aio-mq.*\",condition=\"true\", cluster=\"$cluster\", instance=~\"$namespace\"}[5m])) > 5) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current traffic (includes selftest traffic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Inbound messages / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "subscription(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aio_mq_total_subscriptions{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound messages / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_mq_publishes_sent{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "session(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aio_mq_connected_sessions{hostname=~\".*frontend.*\", cluster=\"$cluster\", instance=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}