{
 "title": "aio-service-mq-payload-check",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=\"$cluster\", phase!~\"terminating\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "# End-to-end metrics\n\nEnd-to-end metrics include publish, subscribe and payload check operations, all measured in a single metric."
   }
  },
  {
   "title": "End-to-end health [%] [Avg]",
   "type": "timeseries",
   "description": "End-to-end health is unhealthy (<100%) if number of lost messages is != 0",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "columns": [
      { "selector": "Correctness", "text": "Health", "type": "number" },
      { "selector": "Time", "text": "Time", "type": "timestamp" }
     ],
     "expr": "1 - min(\r\n    0 * sgn(\r\n        sum(aio_mq_payload_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n    <= 0) or\r\n    1 * sgn(\r\n        sum(aio_mq_payload_check_total_messages_lost{cluster=\"$cluster\", instance=~\"$namespace\"})\r\n    > 0)) or vector(0)",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Avg end-to-end latency [ms] (99th pctl)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "columns": [
      { "selector": "Time", "text": "Time", "type": "timestamp" },
      { "selector": "Mu", "text": "Publish Latency Average", "type": "number" }
     ],
     "expr": "aio_mq_payload_check_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Mean",
     "parser": "simple"
    }
   ]
  },
  {
   "title": "Std dev end-to-end latency [ms] (99th pctl)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "columns": [
      { "selector": "Time", "text": "Time", "type": "timestamp" },
      { "selector": "Sigma", "text": "Publish Latency Variance", "type": "number" }
     ],
     "expr": "aio_mq_payload_check_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Standard deviation"
    }
   ]
  },
  {
   "title": "Avg end-to-end latency [ms] (99th pctl) Control Chart",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "columns": [
      { "selector": "Time", "text": "Time", "type": "timestamp" },
      { "selector": "Mu", "text": "Avg Publish Latency", "type": "number" },
      { "selector": "Min1Sigma", "text": "Minus 1 Sigma", "type": "number" },
      { "selector": "Min2Sigma", "text": "Minus 2 Sigma", "type": "number" },
      { "selector": "LCL", "text": "LCL", "type": "number" },
      { "selector": "Plus1Sigma", "text": "Plus 1 Sigma", "type": "number" },
      { "selector": "Plus2Sigma", "text": "Plus 2 Sigma", "type": "number" },
      { "selector": "UCL", "text": "UCL", "type": "number" },
      { "selector": "LastReading", "text": "Last reading", "type": "number" }
     ],
     "expr": "aio_mq_payload_check_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Mean",
     "parser": "simple"
    },
    {
     "expr": "aio_mq_payload_check_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"} - aio_mq_payload_check_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "1 Std Dev"
    },
    {
     "expr": "aio_mq_payload_check_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"} - 2*aio_mq_payload_check_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "2 Std Dev"
    },
    {
     "expr": "aio_mq_payload_check_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"} - 3*aio_mq_payload_check_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "LCL"
    },
    {
     "expr": "aio_mq_payload_check_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"} + aio_mq_payload_check_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "1 Std Dev"
    },
    {
     "expr": "aio_mq_payload_check_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"} + 2*aio_mq_payload_check_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "2 Std Dev"
    },
    {
     "expr": "aio_mq_payload_check_latency_mu_ms{cluster=\"$cluster\", instance=~\"$namespace\"} + 3*aio_mq_payload_check_latency_sigma_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "UCL"
    },
    {
     "expr": "aio_mq_payload_check_latency_last_value_ms{cluster=\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Last"
    }
   ]
  }
 ]
}