{
 "title": "aio-health-infra-pod",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=~\"$cluster\", phase!~\"terminating\"}"
    }
   },
   {
    "name": "component",
    "query": "AIO-Akri : ^aio-(akri-).*,AIO-Dataflow : ^aio-(dataflow-).*,AIO-MQ : ^aio-(broker-).*,AIO-OPCUABroker : ^aio-(opc-).*,AIO-Orchestrator : ^aio-(cert-|orc-).*,AzMon : ^(ama-|azuremonitor).*,AIO-3P-Support : ^(aio-otel|telegraf).*"
   },
   {
    "name": "pod",
    "query": {
     "query": "container_cpu_usage_seconds_total{container=\"\",cpu=\"total\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\"}"
    }
   },
   {
    "name": "podnamespace",
    "query": {
     "query": "container_cpu_usage_seconds_total{container=\"\",cpu=\"total\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"}"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"}"
    }
   },
   { "name": "logRowLimit", "label": "Log Row Limit", "query": "10,50,100,500,1000" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#283747\">\n  <span style=\"color:#FFFFF8; font-size:28px\">Azure Edge Services - Pod Health</span>\n</div>\n<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Pod Health - $pod</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Health Summary",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\n  kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\",phase=~\"running|succeeded\"} > 0 or\r\n  kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\",phase!~\"running|succeeded\"} > 0 * 0 or\r\n  vector(0)>0\r\n) or vector(-1),\"_\",\"Pod Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Pod Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "sum by(_,value)(\r\n#label_replace(label_replace(\r\n#  (vector(1)\r\n#  ),\"value\",\"$pod\",\"\",\"\"),\"_\",\"Pod:\",\"\",\"\") or\r\nlabel_replace(label_replace(\r\n  (\r\n  sum by(pod)(kube_pod_owner{cluster=~\"$cluster\",pod=~\"$pod\"})\r\n  ),\"value\",\"$1\",\"pod\",\"(.*)\"),\"_\",\"Pod:\",\"\",\"\") or\r\nlabel_replace(label_replace(\r\n  sum by(namespace)(kube_pod_owner{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"}\r\n  ),\"value\",\"$1\",\"namespace\",\"(.*)\"),\"_\",\"Namespace:\",\"\",\"\") or\r\nlabel_replace(label_replace(\r\n  sum by(owner_kind,owner_name)( # Pod owner kind and name\r\n    sum by(replicaset)(label_replace(\r\n      sum by(owner_kind, owner_name)(\r\n        kube_pod_owner{cluster=~\"$cluster\",namespace=~\"$namespace\",owner_kind=\"replicaset\",pod=~\"$component\",pod=~\"$pod\"}\r\n      ),\"replicaset\",\"$1\",\"owner_name\",\"(.*)\"))\r\n    / on (replicaset) group_left(owner_kind, owner_name) \r\n      sum by(owner_kind,owner_name,replicaset)(kube_replicaset_owner{cluster=~\"$cluster\",namespace=~\"$namespace\",replicaset=~\"$component\"})\r\n    or sum by(owner_kind, owner_name)(\r\n      kube_pod_owner{cluster=~\"$cluster\",namespace=~\"$namespace\",owner_kind!=\"replicaset\",pod=~\"$component\",pod=~\"$pod\"}\r\n    )\r\n  ),\"value\",\"$1\",\"owner_kind\",\"(.*)\"),\"_\",\"Type:\",\"\",\"\") or\r\nlabel_replace(label_replace(\r\n  sum by(owner_kind,owner_name)( # Pod owner kind and name\r\n    sum by(replicaset)(label_replace(\r\n      sum by(owner_kind, owner_name)(\r\n        kube_pod_owner{cluster=~\"$cluster\",namespace=~\"$namespace\",owner_kind=\"replicaset\",pod=~\"$component\",pod=~\"$pod\"}\r\n      ),\"replicaset\",\"$1\",\"owner_name\",\"(.*)\"))\r\n    / on (replicaset) group_left(owner_kind, owner_name) \r\n      sum by(owner_kind,owner_name,replicaset)(kube_replicaset_owner{cluster=~\"$cluster\",namespace=~\"$namespace\",replicaset=~\"$component\"})\r\n    or sum by(owner_kind, owner_name)(\r\n      kube_pod_owner{cluster=~\"$cluster\",namespace=~\"$namespace\",owner_kind!=\"replicaset\",pod=~\"$component\",pod=~\"$pod\"}\r\n    )\r\n  ),\"value\",\"$1\",\"owner_name\",\"(.*)\"),\"_\",\"Parent:\",\"\",\"\") or\r\n#label_replace(label_replace(\r\n#  sum by(phase)(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"} > 0\r\n#  ),\"value\",\"$1\",\"phase\",\"(.*)\"),\"_\",\"State:\",\"\",\"\") or\r\nvector(0)>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "sum by(container)(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"}) \r\n/ on (container) group_right sum by(container,image)(\r\n  kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"})\r\n* on (container) group_left #label_replace(\r\n  max by(container)(\r\n  kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "  ",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(_,value)(\r\n#label_replace(label_replace(\r\n#  (vector(1)\r\n#  ),\"value\",\"$pod\",\"\",\"\"),\"_\",\"Pod:\",\"\",\"\") or\r\nlabel_replace(label_replace(\r\n  sum by(phase)(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"}) > 0 or\r\n  label_replace(absent(present_over_time(sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"})[$__rate_interval:])),\"phase\",\"deleted\",\"\",\"\"\r\n  ),\"value\",\"$1\",\"phase\",\"(.*)\"),\"_\",\"State:\",\"\",\"\") or\r\n  vector(0)>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State timeline",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "sum by(_,value)(\r\n#label_replace(label_replace(\r\n#  (vector(1)\r\n#  ),\"value\",\"$pod\",\"\",\"\"),\"_\",\"Pod:\",\"\",\"\") or\r\nlabel_replace(label_replace(\r\n  1*sum by(phase)(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\",phase=\"failed\"}) > 0 or\r\n  2*sum by(phase)(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\",phase=\"pending\"}) > 0 or\r\n  3*sum by(phase)(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\",phase=\"running\"}) > 0 or\r\n  4*sum by(phase)(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\",phase=\"succeeded\"}) > 0 or\r\n  5*sum by(phase)(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\",phase=\"unknown\"}) > 0 or\r\n  0*label_replace(absent(present_over_time(sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$component\",pod=~\"$pod\"})[$__rate_interval:])),\"phase\",\"deleted\",\"\",\"\"\r\n  ),\"value\",\"$1\",\"phase\",\"(.*)\"),\"_\",\"State2:\",\"\",\"\") or\r\n  vector(0)>0)",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "CPU for [$container]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "repeat": "container",
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\n#(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") \r\n#    and label_replace(quantile_over_time(0.95,sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"}[$__rate_interval]))[3d:]) < 0.2,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\")) # Show milli-cores if rate below 0.2 cores\r\n# CPU Time (cores version, if >= 0.2 cores)\r\n#or \r\n(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])),\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") *1000\r\n    #and label_replace(quantile_over_time(0.95,sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"}[$__rate_interval]))[3d:]) >= 0.2,\"_\",\"CPU Usage (cores)\",\"\",\"\")\r\n    ) # Show in cores if rate at or above 0.2 cores\r\n# Shows the max in millicores, used to determine which is shown (commented out for UX; only uncomment to debug above)\r\n#or label_replace(quantile_over_time(0.95,sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"}[$__rate_interval]))[3d:])*1000,\"_\",\"CPU Usage (milli-cores) MAX\",\"\",\"\")\r\n# Sum of all limits defined, in Cores\r\nor label_replace(sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",pod=~\"$pod\",container=~\"$container\",resource=\"cpu\"}),\"_\",\"CPU Limits (milli-cores)\",\"\",\"\")*1000\r\n# CPU Throttling:\r\nor label_replace(100*(max(\r\n        rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",pod=~\"$pod\",container=~\"$container\"}[10m])\r\n        / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",pod=~\"$pod\",container=~\"$container\"}[10m])\r\n    )),\"_\",\"CPU Max Throttled (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory for [$container]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "repeat": "container",
   "targets": [
    {
     "expr": "# Memory Usage (MB version)\r\n(label_replace(sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",pod=~\"$pod\",container=~\"$container\"})/(1024*1024),\"_\",\"Mem Working Bytes (MB)\",\"\",\"\") #and label_replace(max_over_time(sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"})[3d:])/(1024*1024) < 512,\"_\",\"Mem Working Bytes (MB)\",\"\",\"\")\r\n)\r\n# Memory Usage (GB version)\r\n#or (label_replace(sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"})/(1024*1024*1024),\"_\",\"Mem Working Bytes (GB)\",\"\",\"\") and label_replace(quantile_over_time(0.95,sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"})[3d:])/(1024*1024) >= 512,\"_\",\"Mem Working Bytes (GB)\",\"\",\"\"))\r\n### MB vs GB cut-off\r\n##or label_replace(quantile_over_time(0.95,sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"})[3d:])/(1024*1024),\"_\",\"Mem Max Over Time\",\"\",\"\")\r\n# Sum of all limits defined, in Cores\r\nor (label_replace(sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",pod=~\"$pod\",container=~\"$container\",resource=\"memory\"}),\"_\",\"Memory Limits (MB)\",\"\",\"\") / (1024*1024) #and label_replace(quantile_over_time(0.95,sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"})[3d:])/(1024*1024) < 512,\"_\",\"Memory Limits (MB)\",\"\",\"\")\r\n)\r\n#or (label_replace(sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\",resource=\"memory\"}),\"_\",\"Memory Limits (GB)\",\"\",\"\") / (1024*1024*1024) and label_replace(quantile_over_time(0.95,sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container=~\"$container\"})[3d:])/(1024*1024) >= 512,\"_\",\"Memory Limits (GB)\",\"\",\"\"))\r\n# Max Mem % Usage:\r\nor label_replace(100*(max(\r\n    max_over_time((max by(container)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",pod=~\"$pod\",container=~\"$container\"}))[10m:])\r\n    / max by(container)(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",pod=~\"$pod\",container=~\"$container\",resource=\"memory\"})\r\n    )),\"_\",\"Mem Max Usage vs Limit (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Logs</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Kube Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Kube Events entries (for [$pod] up to $logRowLimit events)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubeEvents\r\n| where TimeGenerated > $__timeFrom() and TimeGenerated  <= $__timeTo\r\n| where ClusterName == '$cluster'\r\n//| where Name matches regex '${component:raw}'\r\n| where Name matches regex '$pod'\r\n//| order by TimeGenerated desc\r\n| order by LastSeen desc, FirstSeen desc, TimeGenerated desc\r\n//| project-rename PodName = Name\r\n//| project PodName, Reason, Message, Count, FirstSeen, LastSeen\r\n| project  FirstSeen, LastSeen, Count, Reason, Message\r\n| take $logRowLimit",
      "resources": [
       "/subscriptions/<Placeholder_SubID>"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Container Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Container logs (for [$container], latest $logRowLimit rows)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "repeat": "container",
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let startTime = datetime(${__from:date});\r\nlet nodes = ContainerNodeInventory // ID computers in selected clusters:\r\n| where TimeGenerated >= startTime | summarize by Computer, _ResourceId\r\n| extend Cluster = substring(_ResourceId,strlen(_ResourceId)-indexof(reverse(_ResourceId),'/'))\r\n| project-reorder Cluster, Computer | where Cluster == '$cluster' | take 10 | project Computer; //, Cluster; // nodes;\r\nlet containerInv = ContainerInventory // Get ContainerIds and pod names\r\n| where TimeGenerated >= startTime | join kind=inner nodes on Computer | where ContainerHostname == '$pod'\r\n| summarize by ContainerHostname, Computer, ContainerID, Name | take 100 | project-rename Pod = ContainerHostname \r\n| extend ContainerName = replace_regex(Name, 'k8s_(.*)_${pod}_.*',@'\\1') \r\n| where ContainerName == '${container:raw}'\r\n| project Pod, ContainerName, ContainerID; // containerInv\r\nlet containerIds = containerInv | project ContainerID;\r\nContainerLog\r\n//| where TimeGenerated >= startTime \r\n| where TimeGenerated > $__timeFrom and TimeGenerated  <= $__timeTo\r\n| where Computer in (nodes)\r\n| where ContainerID in (containerIds)\r\n| join kind=inner hint.strategy=shuffle containerInv on ContainerID | project-away ContainerID1, ContainerID, TenantId, SourceSystem, Type, _ResourceId, TimeOfCommand\r\n//| join kind=inner nodes on Computer | project-away Computer1 | project-rename Node = Computer\r\n| extend STD = case(LogEntrySource == 'stdout', 'OUT', LogEntrySource == 'stderr', 'ERR', '???')\r\n//| project TimeGenerated, LogEntrySource, \r\n| order by TimeGenerated desc\r\n| project STD, LogEntry, TimeGenerated //, Node, Cluster\r\n| take $logRowLimit",
      "resources": [
       "/subscriptions/<Placeholder_SubID>"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}