{
 "title": "aio-service-dp-pipeline",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_condition,cluster)"
    }
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": {
     "query": "label_values(aio_dp_runner_info{cluster=\"$cluster\"},cloud_resource_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Reader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
     "legendFormat": "$pipeline"
    }
   ]
  },
  {
   "title": "Messages Written to Message Store",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_processed_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
     "legendFormat": "$pipeline"
    }
   ]
  },
  {
   "title": "Reader Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aio_dp_reader_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le))",
     "legendFormat": "$pipeline"
    }
   ]
  },
  {
   "title": "Reader Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Runner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Stages",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(aio_dp_stage_incoming_messages{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\"}[$__range]) * on(stage_id, runner_partition) group_left(stage_type, stage_name, stage_index) aio_dp_stage_info{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\"}) by (stage_id, stage_type, stage_name, stage_index)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aio_dp_stage_outgoing_messages{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\"}[$__range]) * on(stage_id, runner_partition) group_left(stage_type, stage_name, stage_index) aio_dp_stage_info{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\"}) by (stage_id, stage_type, stage_name, stage_index)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aio_dp_stage_errors{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\"}[$__range]) * on(stage_id, runner_partition) group_left(stage_type, stage_name, stage_index) aio_dp_stage_info{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\"}) by (stage_id, stage_type, stage_name, stage_index)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.50, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]) * on(stage_id, runner_partition) group_left(stage_type, stage_name, stage_index) aio_dp_stage_info{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\"}) by (le, stage_id, stage_type, stage_name, stage_index)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.95, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]) * on(stage_id, runner_partition) group_left(stage_type, stage_name, stage_index) aio_dp_stage_info{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\"}) by (le, stage_id, stage_type, stage_name, stage_index)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.99, sum(rate(aio_dp_stage_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval]) * on(stage_id, runner_partition) group_left(stage_type, stage_name, stage_index) aio_dp_stage_info{cluster=\"$cluster\", cloud_resource_id=\"$pipeline\"}) by (le, stage_id, stage_type, stage_name, stage_index)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner (By partition)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(aio_dp_stage_outgoing_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_id=\"$$input\"}[$__range])) by (runner_partition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aio_dp_stage_incoming_messages{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\", stage_type=~\"^output/.*$\"}[$__range])) by (runner_partition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__range])) by (runner_partition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.50, sum(rate(aio_dp_pipeline_internal_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, runner_partition)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.95, sum(rate(aio_dp_pipeline_internal_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, runner_partition)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.99, sum(rate(aio_dp_pipeline_internal_latency_bucket{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (le, runner_partition)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner Errors by Stage / Error Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__rate_interval])) by (stage_id, stage_type, error_code)",
     "legendFormat": "{{error_code}}: {{stage_id}} ({{stage_type}})"
    }
   ]
  },
  { "title": "Checkpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Incomplete checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(aio_dp_runner_checkpoint_start{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__range]))",
     "legendFormat": "started_checkpoints"
    },
    {
     "expr": "sum(increase(aio_dp_runner_checkpoint_complete{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}[$__range]))",
     "legendFormat": "completed_checkpoints"
    },
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Checkpoint Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(cloud_resource_id) (aio_dp_runner_checkpoint_size{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "aio_dp_runner_checkpoint_error{cluster=\"$cluster\",cloud_resource_id=\"$pipeline\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}