{
 "title": "aio-health-infra-workload",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "label": "namespaces",
    "query": {
     "query": "kube_namespace_status_phase{cluster=~\"$cluster\", phase!~\"terminating\"}"
    }
   },
   {
    "name": "namespace4workloads",
    "query": {
     "query": "kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\"}"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": "AIO-DataProcessor : ^aio-(dp-).*,AIO-MQ : ^aio-(mq-).*,AIO-LayeredNetworkManagement : ^(aio-lnm-|lnm).*,AIO-OPCUABroker : ^aio-(opc-).*,AIO-Orchestrator : ^aio-(cert-|orc-).*,AzMon : ^(ama-|azuremonitor).*,OLD-AKRI : ^(akri-).*,OLD-OBS : ^(obs|lok|flu|otel|pro|tem).*,AIO-3P-Support : ^(aio-otel|telegraf).*"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#283747\">\n  <span style=\"color:#FFFFF8; font-size:28px\">Azure Edge Services - Infrastructure Health</span>\n</div>\n<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Infrastructure Workload Health by Component</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  { "title": "$component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "component" },
  {
   "title": "Health Summary",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n  / label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(-1),\"_\",\"Workload Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Restart Health:\r\n############################\r\nlabel_replace(\r\n  sgn(sum_over_time(sum(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[10m:1m]\r\n    )*60)[1h:]) > 5) * 0.0 # RED: Cumulative restarts over X(5) time greater than Y(1h)\r\n  or (max(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[5m:1m]\r\n    )*60*5) > 0) * 0.5 # YELLOW: restarts detected but below Red threshold\r\n  or sgn(max(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}\r\n    + 1 >= 0))\r\n  #or vector(1) # Healthy\r\n  ,\"_\",\"Container Restart Health\",\"\",\"\")\r\n## uncomment below to t-shoot this health metric\r\n# or label_replace(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[10m:1m])*60)[1h:]),\"_\",\"Total-restarts-over-time\",\"\",\"\")\r\n# or label_replace((max(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[5m:1m])*60*5) without (__name__,uid,instance,job) > 0),\"_\",\"restart\",\"\",\"\") # Base query for counting restarts\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container CPU top-level health\r\n################################\r\nlabel_replace(\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m])\r\n    >= 0.60) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.0\r\nor\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m])\r\n    >= 0.40) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.5\r\nor\r\nmin( # Check to see if container is missing CPU Limits configuration\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"cpu\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n    ) #by (namespace,container) # These are commented out for top-level\r\n,\"_\",\"Container CPU Health\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Memory Health:\r\n###########################\r\nlabel_replace(\r\nmin( # Look for high memory utilization\r\n    0.0 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"memory\",pod=~\"${component:raw}\"}) by (namespace, container)\r\n    ) >= .95) or # show health state of 0 if container memory utilization >= 95%\r\n    0.5 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"memory\",pod=~\"${component:raw}\"}) by (namespace, container)\r\n    ) >= .80) or # show health state of 0.5 if container memory utilization >= 80%\r\n    vector(0)>0\r\n) #by (container) \r\nor\r\nmin( # Look for missing limits which we will show as 0 if missing\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"memory\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n) #by (container) \r\n,\"_\",\"Container Memory health\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum ( # by(workloadType) (\r\n#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n),\"_\",\"Ready\",\"\",\"\")\r\n#  / label_replace(label_join(\r\n#        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\"${component:raw}\"} or\r\n#        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\"${component:raw}\"} or\r\n#        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n#    label_replace(label_join(\r\n#        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\"${component:raw}\"} or\r\n#        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\"${component:raw}\"} or\r\n#        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n#  / label_replace(label_join(\r\n  label_replace(sum(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n    ),\"_\",\"Requested\",\"\",\"\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} \r\n      - kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n      kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} \r\n    - kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"}\r\n    > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n      kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"}\r\n    )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\") # this is to zero if no workloads of this type exist\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"} \r\n      - kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor \r\nlabel_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Container Restarts\r\nlabel_replace(ceil(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[10m:1m])*60)[1h:])),\"_\",\"Restarts\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\n(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n# Percent of containers with limits defined\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"cpu\"}) /\r\n    count(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",cpu=\"total\"}) *100\r\n    ,\"_\",\"Percent containers with CPU Limits (%)\",\"\",\"\")\r\n# CPU Throttling:\r\nor label_replace(100*(max(\r\n        rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n        / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n    )),\"_\",\"CPU Max Throttled (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "# Memory Usage (MB version)\r\n(label_replace(sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"Mem Working Bytes (MB)\",\"\",\"\") )\r\n# Percent containers with limits\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"memory\"}) /\r\n    count(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}) *100\r\n    ,\"_\",\"Percent containers with Memory Limits (%)\",\"\",\"\")\r\n# Max Mem % Usage:\r\nor label_replace(100*(max(\r\n    max_over_time((max by(container)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}))[10m:])\r\n    / max by(container)(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"memory\"})\r\n    )),\"_\",\"Mem Max Usage vs Limit (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "   ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp  Infrastructure Workload Health by Namespace</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  { "title": "$namespace4workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }, "repeat": "namespace4workloads" },
  {
   "title": "Health Summary",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",deployment=~\".*\"} or\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",daemonset=~\".*\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",statefulset=~\".*\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n  / label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",daemonset=~\".*\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",deployment=~\".*\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",statefulset=~\".*\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(-1),\"_\",\"Workload Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Restart Health:\r\n############################\r\nlabel_replace(\r\n  sgn(sum_over_time(sum(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\"}[10m:1m]\r\n    )*60)[1h:]) > 5) * 0.0 # RED: Cumulative restarts over X(5) time greater than Y(1h)\r\n  or (max(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\"}[5m:1m]\r\n    )*60*5) > 0) * 0.5 # YELLOW: restarts detected but below Red threshold\r\n  or sgn(max(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\"}\r\n    + 1 >= 0))\r\n  #or vector(1) # Healthy\r\n  ,\"_\",\"Container Restart Health\",\"\",\"\")\r\n## uncomment below to t-shoot this health metric\r\n# or label_replace(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[10m:1m])*60)[1h:]),\"_\",\"Total-restarts-over-time\",\"\",\"\")\r\n# or label_replace((max(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[5m:1m])*60*5) without (__name__,uid,instance,job) > 0),\"_\",\"restart\",\"\",\"\") # Base query for counting restarts\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container CPU top-level health\r\n################################\r\nlabel_replace(\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",pod=~\".*\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",pod=~\".*\"}[10m])\r\n    >= 0.60) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.0\r\nor\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",pod=~\".*\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",pod=~\".*\"}[10m])\r\n    >= 0.40) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.5\r\nor\r\nmin( # Check to see if container is missing CPU Limits configuration\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",resource=\"cpu\",pod=~\".*\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",pod=~\".*\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n    ) #by (namespace,container) # These are commented out for top-level\r\n,\"_\",\"Container CPU Health\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Memory Health:\r\n###########################\r\nlabel_replace(\r\nmin( # Look for high memory utilization\r\n    0.0 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",resource=\"memory\"}) by (namespace, container)\r\n    ) >= .95) or # show health state of 0 if container memory utilization >= 95%\r\n    0.5 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",resource=\"memory\"}) by (namespace, container)\r\n    ) >= .80) or # show health state of 0.5 if container memory utilization >= 80%\r\n    vector(0)>0\r\n) #by (container) \r\nor\r\nmin( # Look for missing limits which we will show as 0 if missing\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",resource=\"memory\",pod=~\".*\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",container!=\"\",pod=~\".*\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n) #by (container) \r\n,\"_\",\"Container Memory health\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum ( # by(workloadType) (\r\n#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",daemonset=~\".*\"} or\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",deployment=~\".*\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",statefulset=~\".*\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n),\"_\",\"Ready\",\"\",\"\")\r\n#  / label_replace(label_join(\r\n#        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*\"} or\r\n#        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\".*\"} or\r\n#        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n#    label_replace(label_join(\r\n#        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\".*\"} or\r\n#        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*\"} or\r\n#        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n#  / label_replace(label_join(\r\n  label_replace(sum(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",daemonset=~\".*\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",deployment=~\".*\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",statefulset=~\".*\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n    ),\"_\",\"Requested\",\"\",\"\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",daemonset=~\".*\"} \r\n      - kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",daemonset=~\".*\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",daemonset=~\".*\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n      kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",deployment=~\".*\"} \r\n    - kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",deployment=~\".*\"}\r\n    > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n      kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",deployment=~\".*\"}\r\n    )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\") # this is to zero if no workloads of this type exist\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",statefulset=~\".*\"} \r\n      - kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",statefulset=~\".*\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",statefulset=~\".*\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor \r\nlabel_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Container Restarts\r\nlabel_replace(ceil(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\"}[10m:1m])*60)[1h:])),\"_\",\"Restarts\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\n(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n# Percent of containers with limits defined\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\",resource=\"cpu\"}) /\r\n    count(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\",cpu=\"total\"}) *100\r\n    ,\"_\",\"Percent containers with CPU Limits (%)\",\"\",\"\")\r\n# CPU Throttling:\r\nor label_replace(100*(max(\r\n        rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\"}[10m])\r\n        / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\"}[10m])\r\n    )),\"_\",\"CPU Max Throttled (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 52 },
   "targets": [
    {
     "expr": "# Memory Usage (MB version)\r\n(label_replace(sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\"})/(1024*1024),\"_\",\"Mem Working Bytes (MB)\",\"\",\"\") )\r\n# Percent containers with limits\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\",resource=\"memory\"}) /\r\n    count(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\"}) *100\r\n    ,\"_\",\"Percent containers with Memory Limits (%)\",\"\",\"\")\r\n# Max Mem % Usage:\r\nor label_replace(100*(max(\r\n    max_over_time((max by(container)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\"}))[10m:])\r\n    / max by(container)(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\"$namespace4workloads\",pod=~\".*\",container!=\"\",resource=\"memory\"})\r\n    )),\"_\",\"Mem Max Usage vs Limit (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}