{
 "title": "aio-health-service-mq",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "component", "query": "${VAR_COMPONENT}" },
   { "name": "component_text", "query": "${VAR_COMPONENT_TEXT}" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=\"$cluster\", phase!~\"terminating\"}"
    }
   },
   { "name": "latency_percentile", "query": "${VAR_LATENCY_PERCENTILE}" },
   { "name": "latency_quantile_range", "query": "5m,10m,15m,1h,3h,6h" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#283747\">\n  <span style=\"color:#FFFFF8; font-size:28px\">Azure Edge Services - Message Queue Health</span>\n</div>\n<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Scenario Health (SLO/RUM) related to ${component_text}</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(0))\r\n        ,\"url\",\"/d/f41cdbe5-4075-4f05-aeb2-a34b5b46571c/aio-service-mq-connect\",\"\",\"\")\r\n        ,\"_\",\"Authentication failures\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(0))\r\n        ,\"url\",\"/d/f41cdbe5-4075-4f05-aeb2-a34b5b46571c/aio-service-mq-connect\",\"\",\"\")\r\n        ,\"_\",\"Authorization failures\",\"\",\"\") or        \r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            > 0.05)) or vector(0))\r\n        ,\"url\",\"/d/eb3949b9-da3a-4b9e-8573-beb5507617a9/aio-service-mq-clusterperf\",\"\",\"\")\r\n        ,\"_\",\"Backpressure\",\"\",\"\") or\r\n    vector(0) > 0 # Tail; not shown\r\n),\"_\",\"MQ Overall Health\",\"\",\"\")\r\n",
     "legendFormat": "{{_}}"
    },
    {
     "expr": "#label_replace(min(\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(404))\r\n        ,\"url\",\"/d/f41cdbe5-4075-4f05-aeb2-a34b5b46571c/aio-service-mq-connect\",\"\",\"\")\r\n        ,\"_\",\"Authentication failures\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(404))\r\n        ,\"url\",\"/d/f41cdbe5-4075-4f05-aeb2-a34b5b46571c/aio-service-mq-connect\",\"\",\"\")\r\n        ,\"_\",\"Authorization failures\",\"\",\"\") or        \r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            > 0.05)) or vector(404))\r\n        ,\"url\",\"/d/eb3949b9-da3a-4b9e-8573-beb5507617a9/aio-service-mq-clusterperf\",\"\",\"\")\r\n        ,\"_\",\"Backpressure\",\"\",\"\") or\r\n    vector(0) > 0 # Tail; not shown\r\n#),\"_\",\"MQ Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Authentication failure rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (category) (rate(aio_mq_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Authorization failure rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (category) (rate(aio_mq_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Backpressure rejections %",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(clamp( # NOTE: data for percent is really choppy; need to clamp, take rate over longer window (and offset), and then \r\n    # truncate to zero when no backpressure is detected in the $__rate_interval to get a less noisy, more accurate view of percentage\r\n    sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=\"$namespace\"}[60m] offset -30m)) * 100 / \r\n    sum(rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=\"$namespace\"}[60m] offset -30m))\r\n    and sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=\"$namespace\"}[$__rate_interval])) > 0\r\n    or vector(0)\r\n    ,0,100),\"_\",\"Backpressure Rejection %\",\"\",\"\") or\r\nvector(0)>0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped QoS0 Messages %",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(clamp( # NOTE: data for percent is really choppy; need to clamp, take rate over longer window (and offset), and then \r\n    # truncate to zero when no backpressure is detected in the $__rate_interval to get a less noisy, more accurate view of percentage\r\n    sum(rate(aio_mq_qos0_messages_dropped{pod_type=\"BE\", cluster=\"$cluster\", instance=\"$namespace\"}[60m] offset -30m)) * 100 / \r\n    sum(rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=\"$namespace\"}[60m] offset -30m))\r\n    and sum(rate(aio_mq_qos0_messages_dropped{pod_type=\"BE\", cluster=\"$cluster\", instance=\"$namespace\"}[$__rate_interval])) > 0\r\n    or vector(0)\r\n    ,0,100),\"_\",\"Dropped QoS0 Messages %\",\"\",\"\") or\r\nvector(0)>0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Service Health (Synthetics/Self-test)</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace((\r\n        min(aio_mq_ping_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/c58ee063-e5f3-4829-ae8f-0160127759cc/aio-service-mq-ping\",\"\",\"\")\r\n        ,\"_\",\"Ping health\",\"\",\"\") or\r\n    label_replace(label_replace((\r\n        min(aio_mq_publish_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/bf5237d2-7deb-4144-aa46-41e1c1629b30/aio-service-mq-publish\",\"\",\"\")\r\n        ,\"_\",\"Publish health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/b5d606dc-a841-4ec0-b7c5-4f1d37c4e877/aio-service-mq-subscribe\",\"\",\"\")\r\n        ,\"_\",\"Subscribe health\",\"\",\"\") or \r\n    vector(0) > 0 # Tail; not shown\r\n),\"_\",\"MQ Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    },
    {
     "expr": "#label_replace(min(\r\n    label_replace(label_replace((\r\n        min(aio_mq_ping_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/c58ee063-e5f3-4829-ae8f-0160127759cc/aio-service-mq-ping\",\"\",\"\")\r\n        ,\"_\",\"Ping health\",\"\",\"\") or\r\n    label_replace(label_replace((\r\n        min(aio_mq_publish_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/bf5237d2-7deb-4144-aa46-41e1c1629b30/aio-service-mq-publish\",\"\",\"\")\r\n        ,\"_\",\"Publish health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) or vector(404))\r\n        ,\"url\",\"/d/b5d606dc-a841-4ec0-b7c5-4f1d37c4e877/aio-service-mq-subscribe\",\"\",\"\")\r\n        ,\"_\",\"Subscribe health\",\"\",\"\") or \r\n    vector(0) > 0 # Tail; not shown\r\n#),\"_\",\"MQ Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Self-test Details",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "#label_replace(min(\r\n    label_replace(\r\n        (100*avg(aio_mq_ping_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}))\r\n        ,\"_\",\"Ping health\",\"\",\"\") or\r\n    label_replace(\r\n        (100*avg(aio_mq_publish_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}))\r\n        ,\"_\",\"Publish health\",\"\",\"\") or \r\n    label_replace(\r\n        (100*avg(aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}))\r\n        ,\"_\",\"Subscribe health\",\"\",\"\") or \r\n    vector(0) > 0 # Tail; not shown\r\n#),\"_\",\"MQ Overall Health\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Routes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "#label_replace(min(\r\nmax by(_)(label_replace(label_join(\r\n    label_replace(sgn(1+\r\n        (min by(route)(aio_mq_ping_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) < 1)\r\n        ),\"_\",\"Ping health\",\"\",\"\") or\r\n    label_replace(sgn(1+\r\n        (min by(route)(aio_mq_publish_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) < 1)\r\n        ),\"_\",\"Publish health\",\"\",\"\") or \r\n    label_replace(sgn(1+\r\n        (min by(route)(aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\", instance=~\"$namespace\"}) < 1)\r\n        ),\"_\",\"Subscribe health\",\"\",\"\") or \r\n    vector(0) > 0 # Tail; not shown\r\n    ,\"x\",\":\",\"_\",\"route\")\r\n    ,\"_\",\"$2 - unhealthy $1\",\"x\",\"(.*) health:(.*)\")\r\n)#),\"_\",\"MQ Overall Health\",\"\",\"\")\r\nor label_replace(vector(0/0),\"_\",\"hidden-timeline\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Golden Metrics</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Usage/Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "label_replace(quantile_over_time($latency_percentile,\r\n    sum(rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval])\r\n    )[$latency_quantile_range:])\r\n    ,\"_\",\"Inbound (msgs/sec)\",\"\",\"\") or\r\nlabel_replace(quantile_over_time($latency_percentile,\r\n    sum(rate(aio_mq_publishes_sent{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval])\r\n    )[$latency_quantile_range:])\r\n    ,\"_\",\"Outbound (msgs/sec)\",\"\",\"\") or\r\nlabel_replace(\r\n    sum(aio_mq_total_subscriptions{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"})\r\n    ,\"_\",\"Topic Subscriptions\",\"\",\"\") or\r\nlabel_replace(\r\n    sum(aio_mq_connected_sessions{hostname=~\".*frontend.*\", cluster=\"$cluster\", instance=~\"$namespace\"})\r\n    ,\"_\",\"Connected Sessions\",\"\",\"\") or\r\n# label_replace(vector(1),\"_\",\"TODO: Usage/Volume\",\"\",\"\") or\r\nvector(0) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    (\r\n        sum(aio_mq_ping_correctness{cluster=\"$cluster\"}) +\r\n        sum(aio_mq_publish_route_replication_correctness{cluster=\"$cluster\"}) +\r\n        sum(aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\"}) +\r\n    0) / (\r\n        count(aio_mq_ping_correctness{cluster=\"$cluster\"}) +\r\n        count(aio_mq_publish_route_replication_correctness{cluster=\"$cluster\"}) +\r\n        count(aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\"}) +\r\n    0)\r\n    ,\"_\",\".Overall\",\"\",\"\") * 100 or\r\nlabel_replace(\r\n    sum(aio_mq_ping_correctness{cluster=\"$cluster\"}) / \r\n    count(aio_mq_ping_correctness{cluster=\"$cluster\"})\r\n    ,\"_\",\"Ping\",\"\",\"\") * 100 or\r\nlabel_replace(\r\n    sum(aio_mq_publish_route_replication_correctness{cluster=\"$cluster\"}) / \r\n    count(aio_mq_publish_route_replication_correctness{cluster=\"$cluster\"})\r\n    ,\"_\",\"Publish\",\"\",\"\") * 100 or\r\nlabel_replace(\r\n    sum(aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\"}) / \r\n    count(aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\"})\r\n    ,\"_\",\"Subscribe\",\"\",\"\") * 100 or\r\n#label_replace(vector(1),\"_\",\"TODO: Success Rate\",\"\",\"\") or\r\nvector(0) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "#ping_latency_last_value_ms{cluster=\"$cluster\"} or\r\nmax by (_)(\r\n    label_replace(label_replace(label_replace(quantile_over_time($latency_percentile,\r\n        aio_mq_ping_latency_last_value_ms{cluster=\"$cluster\"}[$latency_quantile_range])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"Ping Latency $1\",\"pout\",\"(.*)\") or\r\n    label_replace(label_replace(label_replace(quantile_over_time($latency_percentile,\r\n        aio_mq_publish_latency_last_value_ms{cluster=\"$cluster\"}[$latency_quantile_range])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"Publish Latency $1\",\"pout\",\"(.*)\") or\r\n    label_replace(label_replace(label_replace(quantile_over_time($latency_percentile,\r\n        aio_mq_subscribe_latency_last_value_ms{cluster=\"$cluster\"}[$latency_quantile_range])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"Subscribe Latency $1\",\"pout\",\"(.*)\") or\r\n    vector(0)>0) or\r\n#label_replace(vector(1),\"_\",\"TODO: Latency\",\"\",\"\") or\r\nvector(0)>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "expr": "max by(_)(\r\nlabel_replace(clamp( # NOTE: data for percent is really choppy; need to clamp, take rate over longer window (and offset), and then \r\n    # truncate to zero when no backpressure is detected in the $__rate_interval to get a less noisy, more accurate view of percentage\r\n    sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\"}[60m] offset -30m)) * 100 / \r\n    sum(rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[60m] offset -30m))\r\n    and sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval])) > 0 or vector(0)\r\n    ,0,100),\"_\",\"Backpressure Rejection %\",\"\",\"\") or\r\nlabel_replace(sum by(short_hostname)(\r\n    label_replace(\r\n        sum by(hostname) (ceil(rate(aio_mq_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval])))\r\n        ,\"short_hostname\", \"$1\", \"hostname\", \"aio-mq-dmqtt-backend-(.*)*\"))\r\n    ,\"_\",\"# rejected by $1 (msg/s)\",\"short_hostname\",\"(.*)\") > 0 or\r\n    vector(0)>0\r\n) or\r\n#label_replace(vector(1),\"_\",\"TODO: Saturation\",\"\",\"\") or\r\nvector(0)>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Infrastructure Workload Health</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Health Summary",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n  / label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(0),\"_\",\"Workload Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Restart Health:\r\n############################\r\nlabel_replace(\r\n  sgn(sum_over_time(sum(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[10m:1m]\r\n    )*60)[1h:]) > 5) * 0.0 # RED: Cumulative restarts over X(5) time greater than Y(1h)\r\n  or (max(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[5m:1m]\r\n    )*60*5) > 0) * 0.5 # YELLOW: restarts detected but below Red threshold\r\n  or sgn(max(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}\r\n    + 1 >= 0))\r\n  #or vector(1) # Healthy\r\n  ,\"_\",\"Container Restart Health\",\"\",\"\")\r\n## uncomment below to t-shoot this health metric\r\n# or label_replace(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[10m:1m])*60)[1h:]),\"_\",\"Total-restarts-over-time\",\"\",\"\")\r\n# or label_replace((max(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[5m:1m])*60*5) without (__name__,uid,instance,job) > 0),\"_\",\"restart\",\"\",\"\") # Base query for counting restarts\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container CPU top-level health\r\n################################\r\nlabel_replace(\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m])\r\n    >= 0.60) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.0\r\nor\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m])\r\n    >= 0.40) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.5\r\nor\r\nmin( # Check to see if container is missing CPU Limits configuration\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"cpu\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n    ) #by (namespace,container) # These are commented out for top-level\r\n,\"_\",\"Container CPU Health\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Memory Health:\r\n###########################\r\nlabel_replace(\r\nmin( # Look for high memory utilization\r\n    sgn((\r\n        max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"memory\",pod=~\"${component:raw}\"}) by (namespace, container)\r\n    ) >= .95) - 0.5 # show health state of 0.5 if container memory utilization >= 95%\r\n) #by (container) \r\nor\r\nmin( # Look for missing limits which we will show as 0 if missing\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"memory\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n) #by (container) \r\n,\"_\",\"Container Memory health\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum ( # by(workloadType) (\r\n#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n),\"_\",\"Ready\",\"\",\"\")\r\n#  / label_replace(label_join(\r\n#        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\"${component:raw}\"} or\r\n#        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\"${component:raw}\"} or\r\n#        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n#    label_replace(label_join(\r\n#        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\"${component:raw}\"} or\r\n#        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\"${component:raw}\"} or\r\n#        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n#  / label_replace(label_join(\r\n  label_replace(sum(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n    ),\"_\",\"Requested\",\"\",\"\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} \r\n      - kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n      kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} \r\n    - kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"}\r\n    > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n      kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"}\r\n    )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\") # this is to zero if no workloads of this type exist\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"} \r\n      - kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor \r\nlabel_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "# Container Restarts\r\nlabel_replace(ceil(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[10m:1m])*60)[1h:])),\"_\",\"restarts\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\n(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n# Percent of containers with limits defined\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"cpu\"}) /\r\n    count(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",cpu=\"total\"}) *100\r\n    ,\"_\",\"Percent containers with CPU Limits (%)\",\"\",\"\")\r\n# CPU Throttling:\r\nor label_replace(100*(max(\r\n        rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n        / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n    )),\"_\",\"CPU Max Throttled (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 33 },
   "targets": [
    {
     "expr": "# Memory Usage (MB version)\r\n(label_replace(sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"Mem Working Bytes (MB)\",\"\",\"\") )\r\n# Percent containers with limits\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"memory\"}) /\r\n    count(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}) *100\r\n    ,\"_\",\"Percent containers with Memory Limits (%)\",\"\",\"\")\r\n# Max Mem % Usage:\r\nor label_replace(100*(max(\r\n    max_over_time((max by(container)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}))[10m:])\r\n    / max by(container)(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"memory\"})\r\n    )),\"_\",\"Mem Max Usage vs Limit (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\nmax by(_)(\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum by(pod)(rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"_\",\"$1\",\"pod\",\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") or\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum (rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"_\",\".Overall\",\"\",\"\") or\r\nvector(0)>0)",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\nmax by(_)(\r\nlabel_replace(\r\n    sum by(pod)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"$1\",\"pod\",\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") \r\n)\r\n##(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n##    and label_replace(max_over_time(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))[3d:]) < 0.2,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\")) # Show milli-cores if rate below 0.2 cores\r\n# CPU Time (cores version, if >= 0.2 cores)\r\n##or (label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval])),\"_\",\"CPU Usage (cores)\",\"\",\"\") \r\n##    and label_replace(max_over_time(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))[3d:]) >= 0.2,\"_\",\"CPU Usage (cores)\",\"\",\"\")) # Show in cores if rate at or above 0.2 cores\r\n# Shows the max in millicores, used to determine which is shown (commented out for UX; only uncomment to debug above)\r\n#or label_replace(max_over_time(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))[3d:])*1000,\"_\",\"CPU Usage (milli-cores) MAX\",\"\",\"\")\r\n# Sum of all limits defined, in Cores\r\n##or label_replace(sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"cpu\"}),\"_\",\"CPU Limits (cores)\",\"\",\"\")\r\n# CPU Throttling:\r\n##or label_replace(100*(max(\r\n##        rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n##        / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n##    )),\"_\",\"CPU Max Throttled (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "description": "Click on data series to drill down into pod details",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\nmax by(pod)(\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum by(pod)(rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"_\",\"$1\",\"pod\",\"(.*)\") or #,\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") or\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum (rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"pod\",\".Overall\",\"\",\"\") or\r\nvector(0)>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "description": "Click on data series to drill down into pod details",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "# Memory working bytes\r\nmax by(pod)(\r\nlabel_replace(\r\n    sum by(pod)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"$1\",\"pod\",\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") \r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 53 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Errors & Logs</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last 10 Kube Events entries (from $cluster)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubeEvents\r\n| where TimeGenerated > $__timeFrom() and TimeGenerated  <= $__timeTo\r\n| where ClusterName == '$cluster'\r\n| where Name matches regex '${component:raw}'\r\n//| order by TimeGenerated desc\r\n| order by LastSeen desc, FirstSeen desc, TimeGenerated desc\r\n| project-rename PodName = Name\r\n| project FirstSeen, LastSeen, Count, PodName, Reason, Message\r\n| take 10",
      "resources": [
       "/subscriptions/af342bf1-1ace-41df-902c-47921400551b"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 63 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp ${component_text}-specific</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last 100 Log entries (from $cluster)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "ContainerLogV2\r\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| where _ResourceId contains '$cluster'\r\n| where ContainerName contains \"e4k\"\r\n| order by TimeGenerated desc\r\n| project TimeGenerated, PodName, ContainerName, LogSource, LogMessage\r\n| take 100",
      "resources": [
       "/subscriptions/af342bf1-1ace-41df-902c-47921400551b"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}