{
 "title": "aio-service-mq-ping",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=~\"$cluster\", phase!~\"terminating\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ping Health [%] (Avg)",
   "type": "timeseries",
   "description": "Ping health represents the health of the E4K broker. It is calculated as an average value of ping operation status for each attempt.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(aio_mq_ping_correctness{cluster=~\"$cluster\", instance=~\"$namespace\"})",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Ping Health [%] (Avg) per route",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aio_mq_ping_correctness{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg ping latency [ms] (99th pctl)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aio_mq_ping_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Std dev ping latency [ms] (99th pctl)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aio_mq_ping_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Standard deviation"
    }
   ]
  },
  {
   "title": "Avg ping latency [ms] (99th pctl) Control Chart",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aio_mq_ping_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} - aio_mq_ping_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "1 Std Dev"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} - 2*aio_mq_ping_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "2 Std Dev"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} - 3*aio_mq_ping_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "LCL"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} + aio_mq_ping_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "1 Std Dev"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} + 2*aio_mq_ping_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "2 Std Dev"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms{cluster=~\"$cluster\", instance=~\"$namespace\"} + 3*aio_mq_ping_latency_sigma_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "UCL"
    },
    {
     "expr": "aio_mq_ping_latency_last_value_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "Last"
    }
   ]
  },
  {
   "title": "Ping latency per route [ms]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aio_mq_ping_latency_route_ms{cluster=~\"$cluster\", instance=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}