{
 "title": "aio-service-opcua",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods CPU Utilization [Millicores]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"aio-opc.*|.*opc-ua-connector.*\", cluster=\"$cluster\", container=\"\", image=\"\"}[$__rate_interval])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Memory Utilization [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{pod=~\"aio-opc.*|.*opc-ua-connector.*\", cluster=\"$cluster\", container=\"\", image=\"\"} / (1024*1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Supervisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MQTT Publish Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(aio_opc_mqtt_message_publishing_duration_count{service_name=\"supervisor\", aio_opc_mqtt_publish_result=\"Success\", cluster=\"$cluster\"}[$__rate_interval])) * 100) / sum(rate(aio_opc_mqtt_message_publishing_duration_count{service_name=\"supervisor\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configured Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aio_opc_endpoint_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Pool Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (process_runtime_dotnet_thread_pool_threads_count{exported_job=~\"^.*/supervisor$\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors and Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "ContainerLogV2\r\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| where _ResourceId contains '$cluster'\r\n| where ContainerName == 'aio-opc-supervisor'\r\n| where LogSource == 'stdout'\r\n| where LogMessage startswith '<4>'\r\n| order by TimeGenerated desc\r\n| project TimeGenerated, LogMessage, ContainerName, PodName",
      "resources": [
       "/subscriptions/<Placeholder_SubID>"
      ]
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "MQTT Publish Result Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_mqtt_publish_result) (rate(aio_opc_mqtt_message_publishing_duration_count{service_name=\"supervisor\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{aio_opc_mqtt_publish_result}}"
    }
   ]
  },
  {
   "title": "Number of Assets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aio_opc_asset_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Pool Queue Length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(job) (process_runtime_dotnet_thread_pool_queue_length{service_name=~\"supervisor\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Publishing Latency P95 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_opc_mqtt_message_publishing_duration_bucket{service_name=~\"supervisor\", cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Publishing Latency P99 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(aio_opc_mqtt_message_publishing_duration_bucket{service_name=~\"supervisor\", cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "OPC UA Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "application" },
  {
   "title": "MQTT Publish Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_opc_mqtt_message_publishing_duration_count{service_name=\"connector-sidecar\", aio_opc_mqtt_publish_result=\"Success\", cluster=\"$cluster\"}[$__rate_interval])) / sum(rate(aio_opc_mqtt_message_publishing_duration_count{service_name=\"connector-sidecar\", cluster=\"$cluster\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Changes per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_opc_asset_telemetry_data_change_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connector Thread Pool Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (process_runtime_dotnet_thread_pool_threads_count{service_name=\"opcua-connector\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors and Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "ContainerLogV2\r\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| where _ResourceId contains '$cluster'\r\n| where ContainerName matches regex '(^(opc-ua-).*|.*-opc-ua-.*)'\r\n| where LogSource == 'stdout'\r\n| where LogMessage startswith '<4>'\r\n| order by TimeGenerated desc\r\n| project TimeGenerated, LogMessage, PodName, ContainerName\r\n| take 100",
      "resources": [
       "/subscriptions/<Placeholder_SubID>"
      ]
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "MQTT Publish Result Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_mqtt_publish_result) (rate(aio_opc_mqtt_message_publishing_duration_count{service_name=\"connector-sidecar\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Value Changes per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_opc_asset_telemetry_value_change_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connector Thread Pool Queue Length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (process_runtime_dotnet_thread_pool_queue_length{service_name=\"opcua-connector\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Publishing Latency P95 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_opc_mqtt_message_publishing_duration_bucket{service_name=~\"connector-sidecar\", cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Change Processing Latency P95 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_opc_data_change_processing_duration_bucket{cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidecar Thread Pool Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (process_runtime_dotnet_thread_pool_threads_count{service_name=\"connector-sidecar\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Queue Overflow Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aio_opc_asset_telemetry_value_change_count{cluster=\"$cluster\", aio_opc_value_change_status=\"localoverride\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Publishing Latency P99 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(aio_opc_mqtt_message_publishing_duration_bucket{service_name=~\"connector-sidecar\", cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Processing Latency P95 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_opc_event_processing_duration_bucket{cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidecar Thread Pool Queue Length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (process_runtime_dotnet_thread_pool_queue_length{service_name=\"connector-sidecar\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (aio_opc_output_queue_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}