{
 "title": "aio-service-mq-Current traffic (includes selftest traffic)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=\"$cluster\", phase!~\"terminating\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Inbound messages / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (category) (rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Outbound messages / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (category) (rate(aio_mq_publishes_sent{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Connected sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aio_mq_connected_sessions{hostname=~\".*frontend.*\", cluster=\"$cluster\", instance=~\"$namespace\"})",
     "legendFormat": "Connected sessions"
    }
   ]
  },
  {
   "title": "Topic subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aio_mq_total_subscriptions{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"})",
     "legendFormat": "Topic subscriptions"
    }
   ]
  }
 ]
}