{
 "title": "aio-health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   { "name": "namespace", "query": "azure-iot-operations" },
   { "name": "bf_latency_threshold_ms", "query": "${VAR_BF_LATENCY_THRESHOLD_MS}" },
   {
    "name": "aio_opc_latency_threshold_ms",
    "query": "${VAR_AIO_OPC_LATENCY_THRESHOLD_MS}"
   },
   { "name": "nodeThresholdRed", "query": "${VAR_NODETHRESHOLDRED}" },
   { "name": "nodeThresholdYellow", "query": "${VAR_NODETHRESHOLDYELLOW}" },
   { "name": "opc_slo_sr_goal", "query": "${VAR_OPC_SLO_SR_GOAL}" },
   {
    "name": "opc_slo_publish_latency_ms_goal",
    "query": "${VAR_OPC_SLO_PUBLISH_LATENCY_MS_GOAL}"
   },
   {
    "name": "opc_slo_connect_latency_ms_goal",
    "query": "${VAR_OPC_SLO_CONNECT_LATENCY_MS_GOAL}"
   },
   {
    "name": "orc_latency_threshold_ms",
    "query": "${VAR_ORC_LATENCY_THRESHOLD_MS}"
   },
   { "name": "aio_dp_error_threshold", "query": "${VAR_AIO_DP_ERROR_THRESHOLD}" },
   {
    "name": "aio_dp_nats_utilization_threshold",
    "query": "${VAR_AIO_DP_NATS_UTILIZATION_THRESHOLD}"
   },
   { "name": "aio_dp_error_rate", "query": "${VAR_AIO_DP_ERROR_RATE}" },
   {
    "name": "aio_dp_latency_threshold_ms",
    "query": "${VAR_AIO_DP_LATENCY_THRESHOLD_MS}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#283747; text-align: center\">\n  <span style=\"color:#FFFFF8; font-size:30px\">Azure IoT Operations</span>\n</div>\n<div style=\"background-color:#566573; text-align: center\"> \n  <span style=\"color:white; font-size:28px\">Health Model</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "repeat": "cluster",
   "options": {
    "content": "<div style=\"background-color:#C1C9D1; text-align: center\"> \n  <span style=\"color:black; font-size:20px\"> ${cluster} </span>\n</div>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "AIO Version",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "count by(chartversion) (count by(chartversion) (aio_orc_controller_reconcile_latency_count{cluster=\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scenario Health",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "label_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n       kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\".*\",deployment=~\"^aio-akri-agent.*\"} or\r\n       kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\".*\",daemonset=~\"^aio-akri-agent.*\"} or\r\n       kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\".*\",statefulset=~\"^aio-akri-agent.*\"}\r\n       ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n       ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n /\r\n  label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\".*\",daemonset=~\"^aio-akri-agent.*\"} or\r\n        kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=~\".*\",deployment=~\"^aio-akri-agent.*\"} or\r\n        kube_statefulset_status_replicas{cluster=\"$cluster\",namespace=~\".*\",statefulset=~\"^aio-akri-agent.*\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(-1),\"_\",\"Akri Health\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n    label_replace(\r\n        (min(sgn(rate(\r\n            aio_dp_reader_incoming_messages{cluster=\"$cluster\", cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$__rate_interval]\r\n            )*60)) or vector(-1))\r\n        ,\"_\",\"Self-test Input\",\"\",\"\") or\r\n    label_replace(\r\n        (min(\r\n            0 * sgn(0 < round(sum(increase(aio_dp_stage_errors{cluster=\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$__rate_interval])))) or\r\n            1 * sgn(aio_dp_stage_incoming_messages{cluster=\"$cluster\", stage_type=~\"output/.*\", cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Self-test Stage Errors\",\"\",\"\") or\r\n    label_replace(\r\n        (min(sgn(rate(\r\n            aio_dp_stage_incoming_messages{cluster=\"$cluster\", stage_type=~\"output/.*\", cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[$__rate_interval]\r\n            )*60)) or vector(-1))\r\n        ,\"_\",\"Self-test Output\",\"\",\"\") or\r\n    label_replace(\r\n        (min(\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[5m]\r\n                ))) < $aio_dp_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id=~\"$aio_dp_self_test_pipeline\"}[5m]\r\n                ))) >= $aio_dp_latency_threshold_ms) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Self-test Pipeline Latency\",\"\",\"\") or \r\n    # label_replace(label_replace(\r\n    #     (min(\r\n    #         0 * sgn(max(\r\n    #             100 * sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=\"$cluster\"})\r\n    #             / sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=\"$cluster\"})\r\n    #             ) > 90) or\r\n    #         1 * sgn(max(\r\n    #             100 * sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=\"$cluster\"})\r\n    #             / sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=\"$cluster\"})\r\n    #             ) <= 90) or\r\n    #         vector(0)>0\r\n    #     ) or vector(404))\r\n    #     ,\"url\",\"/d/e17d0b7f-9771-4cb8-adf9-56cbaef3fff6/aio-service-dp-messagestore\",\"\",\"\")\r\n    #     ,\"_\",\"Store Utilization\",\"\",\"\") or \r\n    vector(0)>0\r\n),\"_\",\"DataProcessor Health\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace((\r\n        min(aio_mq_publish_route_replication_correctness{cluster=\"$cluster\"}) or vector(404))\r\n        ,\"url\",\"/d/THdxxxh4z/e4k-publish\",\"\",\"\")\r\n        ,\"_\",\"Publish health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_mq_subscribe_route_replication_correctness{cluster=\"$cluster\"}) or vector(404))\r\n        ,\"url\",\"/d/d0318b5a-4afa-47e3-975f-6b1d2d783849/e4k-subscribe\",\"\",\"\")\r\n        ,\"_\",\"Subscribe health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(aio_mq_unsubscribe_route_replication_correctness{cluster=\"$cluster\"}) or vector(404))\r\n        ,\"url\",\"/d/d2a068a7-e4f0-40cc-bba9-29a263a38c58/aio-service-mq-unsubscribe\",\"\",\"\")\r\n        ,\"_\",\"Unsubscribe health\",\"\",\"\") or \r\n    label_replace(label_replace((\r\n        min(\r\n            1 - min(\r\n                0 * sgn(\r\n                    sum(aio_mq_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n                <= 0) or\r\n                1 * sgn(\r\n                    sum(aio_mq_payload_check_total_messages_lost{cluster=\"$cluster\"})\r\n                > 0)) or vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/c84357d6-e4ef-4459-8348-6049269ace5c/aio-service-mq-payload-check\",\"\",\"\")\r\n        ,\"_\",\"End-to-end health\",\"\",\"\") or         \r\n    vector(0) > 0 # Tail; not shown\r\n),\"_\",\"MessageQueue Health\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n    label_replace(\r\n        (min(\r\n            1 * sgn(\r\n                100*sum(rate(aio_opc_mqtt_message_publishing_duration_count\r\n                    {cluster=\"$cluster\",service_name=\"supervisor\",aio_opc_mqtt_publish_result=\"Success\"}[$__rate_interval]))\r\n                / sum(rate(aio_opc_mqtt_message_publishing_duration_count\r\n                    {cluster=\"$cluster\",service_name=\"supervisor\"}[$__rate_interval]))\r\n                 > 99) or\r\n            0 * sgn(sum(rate(aio_opc_mqtt_message_publishing_duration_count{cluster=\"$cluster\",service_name=\"supervisor\"}[$__rate_interval])) > 0) or\r\n            vector(0)>0\r\n        ) or vector(-1))\r\n        ,\"_\",\"Supervisor Success Rate\",\"\",\"\") or\r\n    label_replace(\r\n        (min(\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_opc_mqtt_message_publishing_duration_bucket{cluster=\"$cluster\",service_name=~\"supervisor\"}[5m]\r\n                ))) < $aio_opc_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_opc_mqtt_message_publishing_duration_bucket{cluster=\"$cluster\",service_name=~\"supervisor\"}[5m]\r\n                ))) >= $aio_opc_latency_threshold_ms) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Supervisor latency\",\"\",\"\") or \r\n    vector(0)>0\r\n),\"_\",\"OPCUA Health\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace(\r\n        (min(\r\n            1 * sgn(\r\n                # Raw Success Rate for MQTT message publishing by app, qos, and opc-ua connector\r\n                label_replace(min by(app,opc_ua_connector)(label_replace(label_replace(\r\n                rate(aio_opc_mqtt_message_publishing_duration_count{cluster=\"$cluster\",aio_opc_mqtt_publish_result=\"success\"}[5m:1m])\r\n                * 100 / rate(aio_opc_mqtt_message_publishing_duration_count{cluster=\"$cluster\"}[5m:1m])\r\n                ,\"app\",\"$1\",\"aio_opc_application\",\"(.*)\")\r\n                ,\"opc_ua_connector\",\"$1\",\"aio_opc_module_name\",\"(.*)\"))\r\n                ,\"_\",\"MQTT Publishing Success Rate\",\"\",\"\")\r\n            >= $opc_slo_sr_goal) or\r\n            0 * sgn(\r\n                # Raw Success Rate for MQTT message publishing by app, qos, and opc-ua connector\r\n                label_replace(min by(app,opc_ua_connector)(label_replace(label_replace(\r\n                rate(aio_opc_mqtt_message_publishing_duration_count{cluster=\"$cluster\",aio_opc_mqtt_publish_result=\"success\"}[5m:1m])\r\n                * 100 / rate(aio_opc_mqtt_message_publishing_duration_count{cluster=\"$cluster\"}[5m:1m])\r\n                ,\"app\",\"$1\",\"aio_opc_application\",\"(.*)\")\r\n                ,\"opc_ua_connector\",\"$1\",\"aio_opc_module_name\",\"(.*)\"))\r\n                ,\"_\",\"MQTT Publishing Success Rate\",\"\",\"\")\r\n            < $opc_slo_sr_goal) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/_dMuZUh4kd/opc-ua-broker-dashboard\",\"\",\"\")\r\n        ,\"_\",\"MQTT Publishing Success Rate\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (min(\r\n            1 * sgn(\r\n                label_replace(min by(app,opc_ua_connector)(label_replace(label_replace(\r\n                rate(aio_opc_session_connect_duration_count{cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_connect_result=\"succeeded\"}[5m:1m])\r\n                * 100 / rate(aio_opc_session_connect_duration_count{cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\"}[5m:1m])\r\n                ,\"app\",\"$1\",\"aio_opc_application\",\"(.*)\")\r\n                ,\"opc_ua_connector\",\"$1\",\"aio_opc_module_name\",\"(.*)\"))\r\n                ,\"_\",\"OPC-UA Connect Success Rate\",\"\",\"\")\r\n            >= $opc_slo_sr_goal) or\r\n            0 * sgn(\r\n                label_replace(min by(app,opc_ua_connector)(label_replace(label_replace(\r\n                rate(aio_opc_session_connect_duration_count{cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_connect_result=\"succeeded\"}[5m:1m])\r\n                * 100 / rate(aio_opc_session_connect_duration_count{cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\"}[5m:1m])\r\n                ,\"app\",\"$1\",\"aio_opc_application\",\"(.*)\")\r\n                ,\"opc_ua_connector\",\"$1\",\"aio_opc_module_name\",\"(.*)\"))\r\n                ,\"_\",\"OPC-UA Connect Success Rate\",\"\",\"\")\r\n            < $opc_slo_sr_goal) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/_dMuZUh4kd/opc-ua-broker-dashboard\",\"\",\"\")\r\n        ,\"_\",\"OPC UA Connect Success Rate\",\"\",\"\") or\r\n\r\n    label_replace(label_replace(\r\n        (min(\r\n            1 * sgn(\r\n                # Raw Latency for MQTT Publishing\r\n                label_replace(\r\n                histogram_quantile(0.95,sum by(le,app,opc_ua_connector)(label_replace(label_replace(\r\n                    rate(aio_opc_mqtt_message_publishing_duration_bucket{cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_mqtt_publish_result=\"success\"}[5m:1m])\r\n                ,\"app\",\"$1\",\"aio_opc_application\",\"(.*)\")\r\n                ,\"opc_ua_connector\",\"$1\",\"aio_opc_module_name\",\"(.*)\")))\r\n                ,\"_\",\"MQTT Publishing P95 Latency\",\"\",\"\") \r\n            <= $opc_slo_publish_latency_ms_goal) or\r\n            0.5 * sgn(\r\n                # Raw Latency for MQTT Publishing\r\n                label_replace(\r\n                histogram_quantile(0.95,sum by(le,app,opc_ua_connector)(label_replace(label_replace(\r\n                    rate(aio_opc_mqtt_message_publishing_duration_bucket{cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_mqtt_publish_result=\"success\"}[5m:1m])\r\n                ,\"app\",\"$1\",\"aio_opc_application\",\"(.*)\")\r\n                ,\"opc_ua_connector\",\"$1\",\"aio_opc_module_name\",\"(.*)\")))\r\n                ,\"_\",\"MQTT Publishing P95 Latency\",\"\",\"\") \r\n            > $opc_slo_publish_latency_ms_goal) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/_dMuZUh4kd/opc-ua-broker-dashboard\",\"\",\"\")\r\n        ,\"_\",\"MQTT Publishing latency\",\"\",\"\") or \r\n\r\n    label_replace(label_replace(\r\n        (min(\r\n            1 * sgn(\r\n                #Raw latency for OPC UA Connect by app and opc-ua connector\r\n                label_replace(\r\n                histogram_quantile(0.95,sum by(le,app,opc_ua_connector)(label_replace(label_replace(\r\n                    rate(aio_opc_session_connect_duration_bucket{cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_connect_result=\"succeeded\"}[5m:1m])\r\n                ,\"app\",\"$1\",\"aio_opc_application\",\"(.*)\")\r\n                ,\"opc_ua_connector\",\"$1\",\"aio_opc_module_name\",\"(.*)\")))\r\n                ,\"_\",\"OPC-UA Connect P95 Latency\",\"\",\"\")\r\n            <= $opc_slo_connect_latency_ms_goal) or\r\n            0 * sgn(\r\n                #Raw latency for OPC UA Connect by app and opc-ua connector\r\n                label_replace(\r\n                histogram_quantile(0.95,sum by(le,app,opc_ua_connector)(label_replace(label_replace(\r\n                    rate(aio_opc_session_connect_duration_bucket{cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_connect_result=\"succeeded\"}[5m:1m])\r\n                ,\"app\",\"$1\",\"aio_opc_application\",\"(.*)\")\r\n                ,\"opc_ua_connector\",\"$1\",\"aio_opc_module_name\",\"(.*)\")))\r\n                ,\"_\",\"OPC-UA Connect P95 Latency\",\"\",\"\")\r\n            > $opc_slo_connect_latency_ms_goal) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"url\",\"/d/_dMuZUh4kd/opc-ua-broker-dashboard\",\"\",\"\")\r\n        ,\"_\",\"OPC-UA Connect latency\",\"\",\"\") or \r\n    vector(0)>0\r\n),\"_\",\"OPCUA SLO\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authentication_failures_total{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authentication_failures_total{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(404))\r\n        ,\"url\",\"/d/f5a5c523-2cb6-42d8-b23f-06b0227fe40b/e4k-connect\",\"\",\"\")\r\n        ,\"_\",\"Authentication failures\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authorization_deny_total{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            <= 20) or\r\n            0 * sgn(\r\n                sum(\r\n                    rate(aio_mq_authorization_deny_total{cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])\r\n                    )\r\n            > 20)) or vector(404))\r\n        ,\"url\",\"/d/f5a5c523-2cb6-42d8-b23f-06b0227fe40b/e4k-connect\",\"\",\"\")\r\n        ,\"_\",\"Authorization failures\",\"\",\"\") or        \r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_mq_backpressure_packets_rejected_total{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_mq_publishes_received_total{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_mq_backpressure_packets_rejected_total{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_mq_publishes_received_total{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05)) or vector(404))\r\n        ,\"url\",\"/d/E19etH24z/e4k-cluster-perf\",\"\",\"\")\r\n        ,\"_\",\"Backpressure\",\"\",\"\") or\r\n    label_replace(label_replace(\r\n        (1 - min(\r\n            1 * sgn(\r\n                sum(rate(aio_mq_qos0_messages_dropped_total{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_mq_publishes_received_total{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            <= 0.05) or\r\n            0 * sgn(\r\n                sum(rate(aio_mq_qos0_messages_dropped_total{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\", category!=\"broker_selftest\"}[2m])) / \r\n                sum(quantile_over_time(.95, rate(aio_mq_publishes_received_total{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[2m])[30m:]))\r\n            > 0.05)) or vector(404))\r\n        ,\"url\",\"/d/eb3949b9-da3a-4b9e-8573-beb5507617a9/aio-service-mq-clusterperf\",\"\",\"\")\r\n        ,\"_\",\"Dropped QoS0 Msgs\",\"\",\"\") or\r\n    vector(0) > 0 # Tail; not shown\r\n),\"_\",\"MessageQueue SLO\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n    label_replace(\r\n        (\r\n            sgn(\r\n                (\r\n                    sum(increase(aio_dp_reader_errors{cluster=\"$cluster\"}[$__rate_interval]) or vector(0)) + \r\n                    sum(increase(aio_dp_stage_errors{cluster=\"$cluster\"}[$__rate_interval]) or vector(0))\r\n                ) / \r\n                (\r\n                    sum(increase(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval]) or vector(0)) + \r\n                    sum(increase(aio_dp_stage_incoming_messages{cluster=\"$cluster\"}[$__rate_interval]) or vector(0))\r\n                )\r\n                > $aio_dp_error_rate\r\n            ) - 1\r\n            or\r\n            sgn(\r\n                sum(increase(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval]) or vector(0)) + \r\n                sum(increase(aio_dp_stage_incoming_messages{cluster=\"$cluster\"}[$__rate_interval]) or vector(0))\r\n                > 0\r\n            )\r\n            or vector(404)\r\n        )\r\n        ,\"_\",\"Pipeline Success Rate\",\"\",\"\")\r\n    or\r\n    label_replace(\r\n        (min(\r\n            sgn(\r\n                max(\r\n                    histogram_quantile(0.95, rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\"}[$__rate_interval]))\r\n                    ) < $aio_dp_latency_threshold_ms\r\n                )\r\n            or\r\n            1 - sgn(\r\n                    max(\r\n                        histogram_quantile(0.95, rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\"}[$__rate_interval]))\r\n                    ) >= $aio_dp_latency_threshold_ms\r\n                )\r\n        ) \r\n        or vector(404))\r\n        ,\"_\",\"Pipeline Internal Latency\",\"\",\"\")\r\n    or        \r\n    label_replace(\r\n        (\r\n            min(\r\n                sgn(\r\n                    sum(rate(aio_dp_reader_processed_heartbeats{cluster=\"$cluster\"}[$__rate_interval]))\r\n                    >= sum(rate(aio_dp_reader_incoming_heartbeats{cluster=\"$cluster\"}[$__rate_interval]))\r\n                )\r\n                or\r\n                sgn(\r\n                    sum(rate(aio_dp_stage_heartbeats{cluster=\"$cluster\"}[$__rate_interval]))\r\n                    >= sum(rate(aio_dp_reader_processed_heartbeats{cluster=\"$cluster\"}[$__rate_interval]))\r\n                )\r\n            )\r\n            or vector(404))\r\n    ,\"_\",\"Pipeline Heartbeats\",\"\",\"\")\r\n    # or\r\n    # label_replace(\r\n    #     (\r\n    #         sgn(\r\n    #             sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=\"$cluster\"}) > 0\r\n    #             and\r\n    #             (sum by(server_id)(nats_varz_jetstream_stats_storage{cluster=\"$cluster\"}) / \r\n    #             sum by(server_id)(nats_varz_jetstream_config_max_storage{cluster=\"$cluster\"}))\r\n    #             <= $aio_dp_nats_utilization_threshold\r\n    #         )\r\n    #     or vector(404))\r\n    # ,\"_\",\"Message Store\",\"\",\"\")\r\n),\"_\",\"DataProcessor SLO\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Workload Health",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\"$namespacem\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n  / label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_statefulset_status_replicas{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(404),\"_\",\"AIO Workload Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Restart Health:\r\n############################\r\nlabel_replace(\r\n  sgn(sum_over_time(sum(rate(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[10m:1m]\r\n    )*60)[1h:]) > 5) * 0.0 # RED: Cumulative restarts over X(5) time greater than Y(1h)\r\n  or (max(rate(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m]\r\n    )*60*5) > 0) * 0.5 # YELLOW: restarts detected but below Red threshold\r\n  or sgn(max(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n    + 1 >= 0))\r\n  #or vector(1) # Healthy\r\n  ,\"_\",\"AIO Container Restarts\",\"\",\"\")\r\n## uncomment below to t-shoot this health metric\r\n# or label_replace(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=\"$cluster\"}[10m:1m])*60)[1h:]),\"_\",\"Total-restarts-over-time\",\"\",\"\")\r\n# or label_replace((max(rate(kube_pod_container_status_restarts_total{cluster=\"$cluster\"}[5m:1m])*60*5) without (__name__,uid,instance,job) > 0),\"_\",\"restart\",\"\",\"\") # Base query for counting restarts\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container CPU top-level health\r\n################################\r\nlabel_replace(\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m])\r\n    >= 0.60) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.0\r\nor\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m])\r\n    >= 0.40) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.5\r\nor\r\nmin( # Check to see if container is missing CPU Limits configuration\r\n    sgn(min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"cpu\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n    ) #by (namespace,container) # These are commented out for top-level\r\n,\"_\",\"AIO Container CPU\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Memory Health:\r\n###########################\r\nlabel_replace(\r\nmin( # Look for high memory utilization\r\n    0.0 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace, container)\r\n    ) >= .95) or # show health state of 0 if container memory utilization >= 95%\r\n    0.5 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace, container)\r\n    ) >= .80) or # show health state of 0.5 if container memory utilization >= 80%\r\n    vector(0)>0\r\n) #by (container) \r\nor\r\nmin( # Look for missing limits which we will show as 0 if missing\r\n    sgn(min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n) #by (container) \r\n,\"_\",\"AIO Container Memory\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Node Health",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "# Node Health Status\r\n####################\r\n# RED (0) if no nodes ready without pressure\r\n# YELLOW (0.5) if at least one node not ready or with pressure\r\n# Green (1.0) otherwise\r\nlabel_replace(\r\n  sum(\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition=\"ready\",status=\"false\"} > 0) * 0 or\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition!=\"ready\",status=\"true\"} > 0) * 0.5 or\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition=\"ready\",status=\"true\"} > 0) * 1\r\n  ) / sum(kube_node_info{cluster=\"$cluster\"})\r\n  ,\"_\",\"Node Readiness\",\"\",\"\")\r\n#or label_replace(sum(kube_node_info),\"_\",\"Node Total Count\",\"\",\"\")\r\n#or label_replace(sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}),\"_\",\"Node Ready Count\",\"\",\"\")\r\n#or label_replace( sum(max by (node) (kube_node_status_condition{condition!=\"Ready\",status=\"true\"})),\"_\", \"Node Pressure Count\",\"\",\"\")\r\n#or label_replace(max by (node) (kube_node_status_condition{condition=\"Ready\",status=\"false\"}),\"_\",\"Node Ready Count\",\"\",\"\")\r\n#or label_replace(max by (node) (kube_node_status_condition{condition!=\"Ready\",status=\"true\"}),\"_\", \"Node Pressure Count\",\"\",\"\")\r\n#or label_replace(sum(sgn(\r\n#   max by (node) (kube_node_status_condition{condition=\"Ready\",status=\"false\"})\r\n# + max by (node) (kube_node_status_condition{condition!=\"Ready\",status=\"true\"})\r\n#  )),\"_\",\"Unhealthy Node Count\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Node CPU Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\"}[5m])) \r\n              + avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\"}[5m]))\r\n        ) * 100) > $nodeThresholdRed)\r\n    or 0.5 * sgn(\r\n        100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\"}[5m])) \r\n              + avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\"}[5m]))\r\n        ) * 100) > $nodeThresholdYellow)\r\n    or 1.0 * sgn(sum by (instance)(node_cpu_seconds_total{cluster=\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n    ,\"_\",\"$1\",\"instance\",\"(.*)\"))\r\n# END inner query\r\n),\"_\",\"Node CPU\", \"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Node Memory Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        (100 * sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - (node_memory_MemFree_bytes{cluster=\"$cluster\"} + node_memory_Buffers_bytes{cluster=\"$cluster\"} + node_memory_Cached_bytes{cluster=\"$cluster\"})) / sum by(instance) (node_memory_MemTotal_bytes{cluster=\"$cluster\"})) > $nodeThresholdRed)\r\n    or 0.5 * sgn(\r\n        (100 * sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - (node_memory_MemFree_bytes{cluster=\"$cluster\"} + node_memory_Buffers_bytes{cluster=\"$cluster\"} + node_memory_Cached_bytes{cluster=\"$cluster\"})) / sum by(instance) (node_memory_MemTotal_bytes{cluster=\"$cluster\"})) > $nodeThresholdYellow)\r\n    or 1.0 * sgn(sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n,\"_\",\"$1\",\"instance\",\"(.*)\"))\r\n# END inner query\r\n),\"_\",\"Node Memory\", \"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Disk Usage Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(node)(label_replace(vector(0)>0\r\n  or 0.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"}) > 10) > $nodeThresholdRed)\r\n  or 0.5 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"}) > 10) > $nodeThresholdYellow)\r\n  or 1.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"})))\r\n,\"node\",\"$1\",\"instance\",\"(.*)\"))\r\nor max by (node) (kube_node_info{cluster=\"$cluster\"}) * -1 # Baseline by node\r\n# END inner query\r\n),\"_\",\"Node Disk\", \"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}