{
 "title": "aio-health-service-orch",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "component", "query": "${VAR_COMPONENT}" },
   { "name": "component_text", "query": "${VAR_COMPONENT_TEXT}" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=~\"$cluster\", phase!~\"terminating\"}"
    }
   },
   {
    "name": "aio_orc_latency_threshold_ms",
    "query": "${VAR_AIO_ORC_LATENCY_THRESHOLD_MS}"
   },
   { "name": "latency_percentile", "query": "${VAR_LATENCY_PERCENTILE}" },
   { "name": "latency_quantile_range", "query": "5m,10m,15m,1h,3h,6h,24h" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#283747\">\n  <span style=\"color:#FFFFF8; font-size:28px\">Azure Edge Services - ${component_text} Health</span>\n</div>\n<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Scenario Health (SLO/RUM) related to ${component_text}</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Service Health (Synthetics/Self-test)</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "label_replace(min(\r\n    label_replace(#label_replace(\r\n        (min(\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_api_operation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) < $aio_orc_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_api_operation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) >= $aio_orc_latency_threshold_ms) or\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_provider_operation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) < $aio_orc_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_provider_operation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) >= $aio_orc_latency_threshold_ms) or\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_controller_validation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) < $aio_orc_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_controller_validation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) >= $aio_orc_latency_threshold_ms) or\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_controller_reconcile_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) < $aio_orc_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_controller_reconcile_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) >= $aio_orc_latency_threshold_ms) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Orchestrator latency P95\",\"\",\"\") or\r\n    label_replace(#label_replace(\r\n        (min(\r\n            0 * sgn(0 < round(sum(increase(aio_orc_api_operation_errors{cluster=\"$cluster\"}[$__rate_interval])))) or\r\n            1 * sgn(aio_orc_api_operation_latency_count{cluster=\"$cluster\"}) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"API Operation errors\",\"\",\"\") or\r\n    label_replace(#label_replace(\r\n        (min(\r\n            0 * sgn(0 < round(sum(increase(aio_orc_provider_operation_errors{cluster=\"$cluster\"}[$__rate_interval])))) or\r\n            1 * sgn(aio_orc_provider_operation_latency_count{cluster=\"$cluster\"}) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Provider Operation errors\",\"\",\"\") or\r\n    vector(0)>0\r\n),\"_\",\"$component_text Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    },
    {
     "expr": "# label_replace(min(\r\n    label_replace(#label_replace(\r\n        (min(\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_api_operation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) < $aio_orc_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_api_operation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) >= $aio_orc_latency_threshold_ms) or\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_provider_operation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) < $aio_orc_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_provider_operation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) >= $aio_orc_latency_threshold_ms) or\r\n            1 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_controller_validation_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) < $aio_orc_latency_threshold_ms) or\r\n            0 * sgn(max(histogram_quantile(0.95, rate(\r\n                aio_orc_controller_reconcile_latency_bucket{cluster=\"$cluster\"}[5m]\r\n                ))) >= $aio_orc_latency_threshold_ms) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Orchestrator latency P95\",\"\",\"\") or\r\n    label_replace(#label_replace(\r\n        (min(\r\n            0 * sgn(0 < round(sum(increase(aio_orc_api_operation_errors{cluster=\"$cluster\"}[$__rate_interval])))) or\r\n            1 * sgn(aio_orc_api_operation_latency_count{cluster=\"$cluster\"}) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"API Operation errors\",\"\",\"\") or\r\n    label_replace(#label_replace(\r\n        (min(\r\n            0 * sgn(0 < round(sum(increase(aio_orc_provider_operation_errors{cluster=\"$cluster\"}[$__rate_interval])))) or\r\n            1 * sgn(aio_orc_provider_operation_latency_count{cluster=\"$cluster\"}) or\r\n            vector(0)>0\r\n        ) or vector(404))\r\n        ,\"_\",\"Provider Operation errors\",\"\",\"\") or\r\n    vector(0)>0\r\n# ),\"_\",\"$component_text Overall Health\",\"\",\"\")",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Golden Metrics</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Usage/Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "label_replace(sum(increase(aio_orc_controller_validation_latency_count{cluster=\"$cluster\"}[$__rate_interval])), \"_\", \"Controller Validation Operation\", \"\", \"\") or\r\nlabel_replace(sum(increase(aio_orc_controller_reconcile_latency_count{cluster=\"$cluster\"}[$__rate_interval])), \"_\", \"Controller Reconcile Operation\", \"\", \"\") or\r\nlabel_replace(sum(increase(aio_orc_api_operation_latency_count{cluster=\"$cluster\"}[$__rate_interval])), \"_\", \"API Operation\", \"\", \"\") or\r\nlabel_replace(sum(increase(aio_orc_provider_operation_latency_count{cluster=\"$cluster\"}[$__rate_interval])), \"_\", \"Provider Operation\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    increase(aio_orc_api_operation_errors{cluster=\"$cluster\"}[$__rate_interval]),\r\n    \"_\",\"API \",\"\",\"\") or\r\nlabel_replace(\r\n    increase(aio_orc_provider_operation_errors{cluster=\"$cluster\"}[$__rate_interval]),\r\n    \"_\",\"Provider \",\"\",\"\")",
     "legendFormat": "{{_}} {{providertype}}.{{operation}} (error: {{errorcode}} )"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "#ping_latency_last_value_ms{cluster=\"$cluster\"} or\r\nmax by (_)(\r\n    label_replace(label_replace(label_replace(#quantile_over_time($latency_percentile,\r\n        histogram_quantile($latency_percentile, sum(rate(aio_orc_api_operation_latency_bucket{cluster=\"$cluster\"}[$latency_quantile_range])) by (le,cloud_resource_id))\r\n        #[$latency_quantile_range:])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"API Operation Latency $1\",\"pout\",\"(.*)\") or\r\n    label_replace(label_replace(label_replace(#quantile_over_time($latency_percentile,\r\n        histogram_quantile($latency_percentile, rate(aio_orc_provider_operation_latency_bucket{cluster=\"$cluster\"}[$latency_quantile_range]))\r\n        #[$latency_quantile_range:])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"Provider Operation Latency $1\",\"pout\",\"(.*)\") or\r\n    label_replace(label_replace(label_replace(#quantile_over_time($latency_percentile,\r\n        histogram_quantile($latency_percentile, rate(aio_orc_controller_reconcile_latency_bucket{cluster=\"$cluster\"}[$latency_quantile_range]))\r\n        #[$latency_quantile_range:])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"Controller Reconcile Latency $1\",\"pout\",\"(.*)\") or\r\n    label_replace(label_replace(label_replace(#quantile_over_time($latency_percentile,\r\n        histogram_quantile($latency_percentile, rate(aio_orc_controller_validation_latency_bucket{cluster=\"$cluster\"}[$latency_quantile_range]))\r\n        #[$latency_quantile_range:])\r\n        ,\"pin\",\"${latency_percentile}\",\"\",\"\"),\"pout\",\"P${1}\",\"pin\",\"^0[.](.*)$\")\r\n        ,\"_\",\"Controller Validation Latency $1\",\"pout\",\"(.*)\") or\r\n    vector(0)>0) or\r\n#label_replace(vector(1),\"_\",\"TODO: Latency\",\"\",\"\") or\r\nvector(0)>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Infrastructure Workload Health</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Health Summary",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n  / label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(0),\"_\",\"Workload Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Restart Health:\r\n############################\r\nlabel_replace(\r\n  sgn(sum_over_time(sum(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[10m:1m]\r\n    )*60)[1h:]) > 5) * 0.0 # RED: Cumulative restarts over X(5) time greater than Y(1h)\r\n  or (max(rate(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[5m:1m]\r\n    )*60*5) > 0) * 0.5 # YELLOW: restarts detected but below Red threshold\r\n  or sgn(max(\r\n    kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}\r\n    + 1 >= 0))\r\n  #or vector(1) # Healthy\r\n  ,\"_\",\"Container Restart Health\",\"\",\"\")\r\n## uncomment below to t-shoot this health metric\r\n# or label_replace(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[10m:1m])*60)[1h:]),\"_\",\"Total-restarts-over-time\",\"\",\"\")\r\n# or label_replace((max(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[5m:1m])*60*5) without (__name__,uid,instance,job) > 0),\"_\",\"restart\",\"\",\"\") # Base query for counting restarts\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container CPU top-level health\r\n################################\r\nlabel_replace(\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m])\r\n    >= 0.60) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.0\r\nor\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}[10m])\r\n    >= 0.40) # If throttle create is greater than this percentage, we'll multiply sgn by 0.5 to show as error (or warning depending on threshold coloring)\r\n    ) # by (namespace,container) # These are commented out for top-level\r\n    * 0.5\r\nor\r\nmin( # Check to see if container is missing CPU Limits configuration\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"cpu\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n    ) #by (namespace,container) # These are commented out for top-level\r\n,\"_\",\"Container CPU Health\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Memory Health:\r\n###########################\r\nlabel_replace(\r\nmin( # Look for high memory utilization\r\n    sgn((\r\n        max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"memory\",pod=~\"${component:raw}\"}) by (namespace, container)\r\n    ) >= .95) - 0.5 # show health state of 0.5 if container memory utilization >= 95%\r\n) #by (container) \r\nor\r\nmin( # Look for missing limits which we will show as 0 if missing\r\n    sgn(min(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",resource=\"memory\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    or # if resource limit missing, we or to below to show namespace/container using CPU without limit as a zero to indicate red\r\n    sgn(min(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",container!=\"\",pod=~\"${component:raw}\"}) by (namespace,container))\r\n    # * 0 # TEMPORARILY DISABLING RED FOR MISSING LIMITS\r\n) #by (container) \r\n,\"_\",\"Container Memory health\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum ( # by(workloadType) (\r\n#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n),\"_\",\"Ready\",\"\",\"\")\r\n#  / label_replace(label_join(\r\n#        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\"${component:raw}\"} or\r\n#        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\"${component:raw}\"} or\r\n#        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "#min(\r\n#  label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n#    label_replace(label_join(\r\n#        kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",deployment=~\"${component:raw}\"} or\r\n#        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",daemonset=~\"${component:raw}\"} or\r\n#        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\"$namespace\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n#  / label_replace(label_join(\r\n  label_replace(sum(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} or\r\n        kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} or\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n#        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n#        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n    ),\"_\",\"Requested\",\"\",\"\")\r\n#  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n#) by (workload) >=0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"} \r\n      - kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n        kube_daemonset_status_number_ready{cluster=~\"$cluster\",namespace=~\".*\",daemonset=~\"${component:raw}\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(#sgn(\r\n      kube_deployment_spec_replicas{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"} \r\n    - kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"}\r\n    > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n    sum(#sgn(\r\n      kube_deployment_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",deployment=~\"${component:raw}\"}\r\n    )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor label_replace(vector(0),\"status\",\"Ready\",\"\",\"\") # this is to zero if no workloads of this type exist\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"} \r\n      - kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n      > 0)#)\r\n  ,\"status\",\"Not-Ready\",\"\",\"\")\r\nor \r\nlabel_replace(\r\n      sum(#sgn(\r\n        kube_statefulset_status_replicas_ready{cluster=~\"$cluster\",namespace=~\".*\",statefulset=~\"${component:raw}\"}\r\n      )#)\r\n  ,\"status\",\"Ready\",\"\",\"\")\r\nor \r\nlabel_replace(vector(0),\"status\",\"Ready\",\"\",\"\")\r\n# or label_replace(vector(1),\"status\",\"Not-Ready\",\"\",\"\") # UNCOMMENT THIS LINE TO TEST \"NOT-READY\" STATUS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "# Container Restarts\r\nlabel_replace(ceil(sum_over_time(sum(rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\"}[10m:1m])*60)[1h:])),\"_\",\"restarts\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\n(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n# Percent of containers with limits defined\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"cpu\"}) /\r\n    count(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",cpu=\"total\"}) *100\r\n    ,\"_\",\"Percent containers with CPU Limits (%)\",\"\",\"\")\r\n# CPU Throttling:\r\nor label_replace(100*(max(\r\n        rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n        / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n    )),\"_\",\"CPU Max Throttled (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 25 },
   "targets": [
    {
     "expr": "# Memory Usage (MB version)\r\n(label_replace(sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"Mem Working Bytes (MB)\",\"\",\"\") )\r\n# Percent containers with limits\r\nor label_replace(\r\n    count(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"memory\"}) /\r\n    count(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}) *100\r\n    ,\"_\",\"Percent containers with Memory Limits (%)\",\"\",\"\")\r\n# Max Mem % Usage:\r\nor label_replace(100*(max(\r\n    max_over_time((max by(container)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}))[10m:])\r\n    / max by(container)(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"memory\"})\r\n    )),\"_\",\"Mem Max Usage vs Limit (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\nmax by(_)(\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum by(pod)(rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"_\",\"$1\",\"pod\",\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") or\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum (rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"_\",\".Overall\",\"\",\"\") or\r\nvector(0)>0)",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\nmax by(_)(\r\nlabel_replace(\r\n    sum by(pod)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"$1\",\"pod\",\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") \r\n)\r\n##(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n##    and label_replace(max_over_time(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))[3d:]) < 0.2,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\")) # Show milli-cores if rate below 0.2 cores\r\n# CPU Time (cores version, if >= 0.2 cores)\r\n##or (label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval])),\"_\",\"CPU Usage (cores)\",\"\",\"\") \r\n##    and label_replace(max_over_time(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))[3d:]) >= 0.2,\"_\",\"CPU Usage (cores)\",\"\",\"\")) # Show in cores if rate at or above 0.2 cores\r\n# Shows the max in millicores, used to determine which is shown (commented out for UX; only uncomment to debug above)\r\n#or label_replace(max_over_time(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[$__rate_interval]))[3d:])*1000,\"_\",\"CPU Usage (milli-cores) MAX\",\"\",\"\")\r\n# Sum of all limits defined, in Cores\r\n##or label_replace(sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\",resource=\"cpu\"}),\"_\",\"CPU Limits (cores)\",\"\",\"\")\r\n# CPU Throttling:\r\n##or label_replace(100*(max(\r\n##        rate(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n##        / rate(container_cpu_cfs_periods_total{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"}[10m])\r\n##    )),\"_\",\"CPU Max Throttled (%)\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "description": "Click on data series to drill down into pod details",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "# CPU Time (milli-cores version, if < 0.2 cores)\r\nmax by(pod)(\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum by(pod)(rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"_\",\"$1\",\"pod\",\"(.*)\") or #,\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") or\r\n    label_replace(#quantile_over_time($latency_percentile,(\r\n        sum (rate(\r\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"${component:raw}\",container!=\"\"}\r\n        [$__rate_interval]))#)[$latency_quantile_range:])\r\n        *1000,\"pod\",\".Overall\",\"\",\"\") or\r\nvector(0)>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "description": "Click on data series to drill down into pod details",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "# Memory working bytes\r\nmax by(pod)(\r\nlabel_replace(\r\n    sum by(pod)(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\".*\",pod=~\"${component:raw}\",container!=\"\"})/(1024*1024),\"_\",\"$1\",\"pod\",\"(.*)(-[0-9]$|-[0-9]$|-[^-]+-.....$)\") \r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp Errors & Logs</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last 10 Kube Events entries (from $cluster)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubeEvents\r\n//| where TimeGenerated > ago(1d)\r\n| where ClusterName == '$cluster'\r\n| where Name matches regex '${component:raw}'\r\n//| order by TimeGenerated desc\r\n| order by LastSeen desc, FirstSeen desc, TimeGenerated desc\r\n| project-rename PodName = Name\r\n| project FirstSeen, LastSeen, Count, PodName, Reason, Message\r\n| take 10",
      "resources": [
       "/subscriptions/af342bf1-1ace-41df-902c-47921400551b"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 },
   "options": {
    "content": "<div style=\"background-color:#595959; text-align: left\"> \n  <span style=\"color:white; font-size:18px\">&nbsp ${component_text}-specific</span>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Controller Validation Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, aio_orc_controller_validation_latency_bucket{cluster=\"$cluster\"})",
     "legendFormat": " {{resourcetype}} {{validationtype}} ({{validationresult}})  "
    }
   ]
  },
  {
   "title": "Controller Reconcile Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(resourcetype, reconciliationtype, reconciliationresult) (histogram_quantile(0.95, aio_orc_controller_reconcile_latency_bucket{cluster=\"$cluster\"}))",
     "legendFormat": "{{resourcetype}} {{reconciliationtype}} ({{reconciliationresult}})"
    }
   ]
  },
  {
   "title": "API Operation Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, aio_orc_api_operation_latency_bucket{cluster=\"$cluster\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Provider Operation Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, aio_orc_provider_operation_latency_bucket{cluster=\"$cluster\"})",
     "legendFormat": "{{providertype}}  {{functionname}}"
    }
   ]
  }
 ]
}