{
 "title": "aio-service-dp-overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_condition,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_incoming_messages{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_incoming_messages{cluster=\"$cluster\",stage_type=~\"output/.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_errors{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(rate(aio_dp_reader_errors{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "E2E Latency (95th Percentile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cloud_resource_id, runner_partition) (rate(aio_dp_runner_info{cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cloud_resource_id, stage_id) (rate(aio_dp_stage_info{cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Throughputs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(aio_dp_stage_outgoing_messages{cluster=\"$cluster\",stage_type=~\"messagestore/.*\"}[$__range])) by (cloud_resource_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aio_dp_stage_incoming_messages{cluster=\"$cluster\",stage_type=~\"output/.*\"}[$__range])) by (cloud_resource_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aio_dp_stage_errors{cluster=\"$cluster\"}[$__range])) by (cloud_resource_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Latencies",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time((histogram_quantile(0.95, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le, cloud_resource_id)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.95, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le, cloud_resource_id)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((histogram_quantile(0.99, sum(rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le, cloud_resource_id)) >= 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Self Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "# [Click for Detailed View of Self-test Pipeline](/d/4f637c27-a19f-489e-a4af-719f1baa0a19/aio-service-dp-pipeline?orgId=1&${cluster:queryparam}&var-pipeline=alice-springs%2Fself-test-pipeline&${__url_time_range})"
   }
  },
  {
   "title": "Successful Self-Test messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(aio_dp_stage_incoming_messages{cluster=\"$cluster\",stage_type=~\"output/.*\", cloud_resource_id=~\".*self-test.*\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Failed Self-Test Messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Self-Test Pipeline Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id=~\".*self-test.*\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id=~\".*self-test.*\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(aio_dp_pipeline_latency_bucket{cluster=\"$cluster\",cloud_resource_id=~\".*self-test.*\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true
  },
  {
   "title": "Incomplete checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Checkpointing Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_runner_checkpoint_error{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Checkpoint size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(cloud_resource_id) (aio_dp_runner_checkpoint_size{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Heartbeats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Reader Generated Heartbeats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_incoming_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reader Processed Heartbeats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_reader_processed_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage Processed Heartbeats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_dp_stage_heartbeats{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Pod CPU Usage (% of one CPU core)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=~\"aio-dp-.*\"}[$__rate_interval]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (MiB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=\"$cluster\",container=~\"aio-dp-.*\"} / (1024*1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Version",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "(\r\n    sum(rate(aio_dp_reader_incoming_messages{cluster=~\"$cluster\"}[$__rate_interval])) by (container_image_tag, container_name) or on (container_name)\r\n    clamp_max(absent(notExists{container_name=\"aio-dp-reader-worker\", container_image_tag=\" \"}),0)\r\n) or\r\n(\r\n    sum(rate(aio_dp_runner_info{cluster=~\"$cluster\"}[$__rate_interval])) by (container_image_tag, container_name) or on (container_name)\r\n    clamp_max(absent(notExists{container_name=\"aio-dp-runner-worker\", container_image_tag=\" \"}),0)\r\n) or\r\n(\r\n    sum(rate(aio_dp_refdata_global_ingest_count{cluster=~\"$cluster\"}[$__rate_interval])) by (container_image_tag, container_name) or on (container_name)\r\n    clamp_max(absent(notExists{container_name=\"aio-dp-refdata-store\", container_image_tag=\" \"}), 0)\r\n) or\r\n(\r\n    sum(rate(aio_dp_reconcile_event{cluster=~\"$cluster\"}[$__rate_interval])) by (container_image_tag, container_name) or on (container_name)\r\n    clamp_max(absent(notExists{container_name=\"manager\", container_image_tag=\" \"}), 0)\r\n)",
     "legendFormat": "{{_}}"
    }
   ]
  },
  {
   "title": "Service Pod Count",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "(\r\n    count(count(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container=\"aio-dp-reader-worker\"}) by (container, pod)) by (container) or on (container)\r\n    clamp_max(absent(notExists{container=\"aio-dp-reader-worker\"}),0)\r\n) or\r\n(\r\n    count(count(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container=\"aio-dp-runner-worker\"}) by (container, pod)) by (container) or on (container)\r\n    clamp_max(absent(notExists{container=\"aio-dp-runner-worker\"}),0)\r\n) or\r\n(\r\n    count(count(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container=\"aio-dp-refdata-store\"}) by (container, pod)) by (container) or on (container)\r\n    clamp_max(absent(notExists{container=\"aio-dp-refdata-store\"}), 0)\r\n) or\r\n(\r\n    count(count(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container=\"manager\", pod=~\"aio-dp-.*\"}) by (container, pod)) by (container) or on (container)\r\n    clamp_max(absent(notExists{container=\"manager\"}), 0)\r\n)",
     "legendFormat": "{{_}}"
    }
   ]
  }
 ]
}