{
 "title": "aio-service-mq-ClusterPerf",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "kube_node_info{cluster=\"$cluster\", instance=~\"$namespace\"}"
    }
   },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "kube_node_status_condition" } },
   {
    "name": "namespace",
    "query": {
     "query": "kube_namespace_status_phase{cluster=\"$cluster\", phase!~\"terminating\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods CPU Utilization [Millicores]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"aio-mq.*\", cluster=\"$cluster\"}[$__rate_interval]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall CPU Utilization per node [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node.*\", job=\"node-exporter\", mode=\"idle\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Pods Memory Utilization [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{pod=~\"aio-mq.*\", container!=\"\", cluster=\"$cluster\"} / (1024*1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Memory Utilization per node [%]",
   "type": "timeseries",
   "description": "Memory Utilization is calculated as used memory of node / total available memory",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(node_memory_MemTotal_bytes{instance=~\"$node.*\", cluster=\"$cluster\", instance=~\"$namespace\"} - node_memory_MemFree_bytes{instance=~\"$node.*\", cluster=\"$cluster\", instance=~\"$namespace\"} - node_memory_Buffers_bytes{instance=~\"$node.*\", cluster=\"$cluster\", instance=~\"$namespace\"} - node_memory_Cached_bytes{instance=~\"$node.*\", cluster=\"$cluster\", instance=~\"$namespace\"}) / sum(node_memory_MemTotal_bytes{instance=~\"$node.*\", cluster=\"$cluster\", instance=~\"$namespace\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pods Number Of Restarts",
   "type": "timeseries",
   "description": "Number of pod restarts in the last 5 mins",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod)(changes(kube_pod_status_ready{pod=~\"aio-mq.*\",condition=\"true\", cluster=\"$cluster\", instance=~\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backpressure rejections %",
   "type": "timeseries",
   "description": "Rate of change each second for number of messages rejected due to backpressure over number of received publish messages",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(clamp( # NOTE: data for percent is really choppy; need to clamp, take rate over longer window (and offset), and then \r\n    # truncate to zero when no backpressure is detected in the $__rate_interval to get a less noisy, more accurate view of percentage\r\n    sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\"}[60m] offset -30m)) * 100 / \r\n    sum(rate(aio_mq_publishes_received{pod_type=\"FE\", cluster=\"$cluster\", instance=~\"$namespace\"}[60m] offset -30m))\r\n    and sum(rate(aio_mq_backpressure_packets_rejected{pod_type=\"BE\", cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval])) > 0\r\n    or vector(0)\r\n    ,0,100),\"_\",\"Backpressure Rejection %\",\"\",\"\") or\r\nvector(0)>0",
     "legendFormat": "Backpressure rejections %"
    }
   ]
  },
  {
   "title": "Rate of rejected messages by backend chain due to backpressure [msg / s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "label_replace(sum by(short_hostname)(\r\n    label_replace(\r\n        sum by(hostname) (ceil(rate(aio_mq_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\"}[$__rate_interval])))\r\n        ,\"short_hostname\", \"$1\", \"hostname\", \"aio-mq-dmqtt-backend-(.*)*\"))\r\n    ,\"_\",\"# rejected by $1\",\"short_hostname\",\"(.*)\") or\r\nvector(0)>0",
     "legendFormat": "{{short_hostname}}"
    }
   ]
  }
 ]
}