{
 "title": "aio-service-dp-messagestore",
 "description": "Data Processor message store dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_condition,cluster)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(nats_server_total_streams, server_id)"
    }
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {
     "query": "label_values(nats_stream_last_seq, stream_name)"
    }
   },
   {
    "name": "consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(nats_consumer_num_pending, consumer_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{cluster=\"$cluster\",server_id=~\"$server\"})/sum(nats_varz_jetstream_config_max_storage{cluster=\"$cluster\",server_id=~\"$server\"})"
    },
    {}
   ]
  },
  {
   "title": "Total Storage Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{cluster=\"$cluster\",server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_memory{cluster=\"$cluster\",server_id=~\"$server\"})/sum(nats_varz_jetstream_config_max_memory{cluster=\"$cluster\",server_id=~\"$server\"})"
    },
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_memory{cluster=\"$cluster\",server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_connections{cluster=\"$cluster\",server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Max Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_config_max_storage{cluster=\"$cluster\",server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_config_max_memory{cluster=\"$cluster\",server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_server_total_consumers{cluster=\"$cluster\",server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Stream metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stream data size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_bytes{cluster=\"$cluster\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Stream message count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_messages{cluster=\"$cluster\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Message Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_stream_total_messages{cluster=\"$cluster\",server_id=~\"$server\",stream_name=~\"$stream\"}[$__rate_interval])) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Consumer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages per second (++/--)",
   "type": "timeseries",
   "description": "Messages added & processed per minute per consumer",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_num_pending{cluster=\"$cluster\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}[$__rate_interval])+rate(nats_consumer_delivered_consumer_seq{cluster=\"$cluster\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}} +"
    },
    {
     "expr": "- sum(rate(nats_consumer_delivered_consumer_seq{cluster=\"$cluster\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\",consumer_name=~\"$consumer\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}} -"
    }
   ]
  },
  {
   "title": "Total delivered messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_delivered_consumer_seq{cluster=\"$cluster\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Pending messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_pending{cluster=\"$cluster\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Message Acks Pending",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_ack_pending{cluster=\"$cluster\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  }
 ]
}